# Generated by Django 5.2 on 2026-02-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentikate", "0004_device_client_device"),
        ("core", "0006_rename_name_descriptor_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphSchemaDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this schema version",
                        max_length=255,
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(
                        default=dict,
                        help_text="The schema definition containing node labels, properties, and validation rules",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Schema version for evolution tracking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schema version is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="The graph this schema applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_definitions",
                        to="core.graph",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this schema belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_schemas",
                        to="authentikate.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graph Schema Definition",
                "verbose_name_plural": "Graph Schema Definitions",
                "ordering": ["-version"],
                "unique_together": {("graph", "version")},
            },
        ),
    ]
