# Generated by Django 6.0.3 on 2026-08-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0010_graph_age_name_is_a_handle'),
        ('evidence', '0010_comment_is_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='age', help_text='Which kind of projection this is. Only Apache AGE exists today; the column is the seam for a second kind.', max_length=32)),
                ('status', models.CharField(choices=[('consistent', 'Consistent'), ('needs_backfill', 'Needs backfill'), ('rebuilding', 'Rebuilding')], default='needs_backfill', max_length=32)),
                ('derived_through_seq', models.BigIntegerField(default=0, help_text='Informational: `Max(Assertion.seq)` of the organization when the last bulk operation (rebuild, backfill, incremental replay) read the log. Not the cursor — that is derived, see `graph_engine.watermark.cursor`.')),
                ('schema_hash', models.CharField(blank=True, help_text="`GraphSchema.hash` this drawing was last fully derived under. Differs from the active schema's hash when a category's rules moved and the vertices have not been redrawn — what `manage.py rematerialize --stale` selects on.", max_length=64, null=True)),
                ('derived_at', models.DateTimeField(blank=True, help_text='When `projector.project` last wrote derived properties into this drawing.', null=True)),
                ('rebuilt_at', models.DateTimeField(blank=True, help_text='When this drawing was last dropped and replayed in full.', null=True)),
                ('graph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projection', to='core.graph')),
            ],
            options={
                'default_related_name': 'projections',
            },
        ),
        migrations.CreateModel(
            name='PendingProjection',
            fields=[
                ('assertion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pending_projection', serialize=False, to='evidence.assertion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_projections', to='authentikate.organization')),
            ],
            options={
                'default_related_name': 'pending_projections',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='graph_engin_organiz_f21268_idx')],
            },
        ),
    ]
