# Generated by Django 6.0.3 on 2026-08-31 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_saved_queries_are_plans'),
        ('graph_engine', '0002_projection_rows_for_existing_graphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='kind',
            field=models.CharField(default='table', help_text='Which kind of projection this is. Only the table kind exists today; the column is the seam for a second kind.', max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectionVertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(help_text="The drawn claim's uuid. A value, not a FK: the drawing never holds evidence in place.")),
                ('label', models.CharField(help_text="The view's word for the category (`Category.age_name`).", max_length=1000)),
                ('category_pk', models.BigIntegerField(blank=True, help_text='The category row that admitted this node.', null=True)),
                ('kind', models.CharField(help_text="The claim's `Instance.Kind` (ENTITY, NATURAL_EVENT, PROTOCOL_EVENT).", max_length=32)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Derived properties only; identity lives in the columns.')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_vertices', to='core.graph')),
            ],
            options={
                'default_related_name': 'projection_vertices',
            },
        ),
        migrations.CreateModel(
            name='ProjectionEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="The view's word for the edge category (`Category.age_name`).", max_length=1000)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_edges', to='core.graph')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='graph_engine.projectionvertex')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='graph_engine.projectionvertex')),
            ],
            options={
                'default_related_name': 'projection_edges',
            },
        ),
        migrations.AddIndex(
            model_name='projectionvertex',
            index=models.Index(fields=['graph', 'label'], name='graph_engin_graph_i_d01b3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectionvertex',
            constraint=models.UniqueConstraint(fields=('graph', 'ref'), name='one_vertex_per_ref_per_view'),
        ),
        migrations.AddIndex(
            model_name='projectionedge',
            index=models.Index(fields=['graph', 'label'], name='graph_engin_graph_i_712c0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectionedge',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'label'), name='one_edge_per_endpoints_and_label'),
        ),
    ]
