# Generated by Django 6.0.3 on 2026-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_category_graph_and_id'),
        ('graph_engine', '0003_alter_projection_kind_projectionvertex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionvertex',
            name='category_pk',
            field=models.BigIntegerField(blank=True, help_text='The category row that admitted this node. A plain integer to Django, but backed by a raw composite foreign key `(graph_id, category_pk) REFERENCES core_category (graph_id, id)` ON DELETE CASCADE (migration 0005 — Django cannot express a composite FK), so the database itself refuses a vertex drawn under a category its graph does not declare, and a deleted category takes its drawings with it. NULL passes the constraint (MATCH SIMPLE): only rows an older projector drew carry it, and `manage.py reproject` is their repair. RFC 0006.', null=True),
        ),
        migrations.AddIndex(
            model_name='projectionvertex',
            index=models.Index(fields=['graph', 'category_pk'], name='graph_engin_graph_i_f09928_idx'),
        ),
    ]
