# Generated by Django 5.2 on 2026-03-16 12:30

import core.models
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_name",
                    models.CharField(
                        help_text="The name of the graph class in the age graph",
                        max_length=1000,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The entity key that the node relates to (e.g. a cell line, a cell type, etc.)",
                        max_length=1000,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of category",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "purl",
                    models.CharField(
                        help_text="The PURL (Persistent Uniform Resource Locator)",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.JSONField(
                        default=core.models.random_color,
                        help_text="The color of the entity class as RGB",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label of the node class",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "ports",
                    models.JSONField(
                        default=list,
                        help_text="The ports of the node class ssin the graph (if a node)",
                        null=True,
                    ),
                ),
            ],
            options={
                "default_related_name": "categories",
            },
        ),
        migrations.CreateModel(
            name="CategoryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="The value of the tag", max_length=1000),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the tag", max_length=1000, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the tag",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "default_related_name": "category_tags",
            },
        ),
        migrations.CreateModel(
            name="Descriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The name of the descriptor", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the descriptor",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        help_text="The value of the descriptor", max_length=1000
                    ),
                ),
            ],
            options={
                "default_related_name": "descriptors",
            },
        ),
        migrations.CreateModel(
            name="EdgeQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key of the query, used for referencing the query in the frontend and for pinning it",
                        max_length=1000,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The query that is used to materialize the graph",
                        max_length=7000,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the materialized graph", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the materialized graph",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="The kind of the materialized graph (i.e path, property, etc.)",
                        max_length=1000,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "edge_queries",
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_deletion_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="If node deletion is allowed in this graph",
                    ),
                ),
                (
                    "edge_deletion_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="If edge deletion is allowed in this graph",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the entity group", max_length=1000
                    ),
                ),
                (
                    "purl",
                    models.CharField(
                        blank=True,
                        help_text="The name of the entity group",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the entity group",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "age_name",
                    models.CharField(
                        help_text="The name of the graph class in the age graph",
                        max_length=1000,
                        unique=True,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Action-level allow/deny rules evaluated against request context",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key of the query, used for referencing the query in the frontend and for pinning it",
                        max_length=1000,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The query that is used to materialize the graph",
                        max_length=7000,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the materialized graph", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the materialized graph",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="The kind of the materialized graph (i.e path, property, etc.)",
                        max_length=1000,
                    ),
                ),
                (
                    "returns",
                    models.JSONField(
                        default=list, help_text="The returns of the query", null=True
                    ),
                ),
                (
                    "matches",
                    models.JSONField(
                        default=list, help_text="The matches of the query", null=True
                    ),
                ),
                (
                    "wheres",
                    models.JSONField(
                        default=list, help_text="The wheres of the query", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "graph_queries",
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="GraphOntology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the ontology", max_length=1000
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="The URL of the ontology", max_length=2000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the ontology",
                        max_length=2000,
                        null=True,
                    ),
                ),
            ],
            options={
                "default_related_name": "graph_ontologies",
            },
        ),
        migrations.CreateModel(
            name="GraphSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version of this schema (e.g., '1.0.0')",
                        max_length=100,
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="Sequential index of this schema version (auto-incremented)"
                    ),
                ),
                (
                    "definition",
                    models.JSONField(help_text="The full GraphDefinitionModel as JSON"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the currently active schema for the graph",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of changes in this schema version",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-index"],
            },
        ),
        migrations.CreateModel(
            name="GraphSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        help_text="The index name that was created", max_length=1000
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label of the sequence",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the sequence",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_value", models.IntegerField(default=0)),
                ("start_value", models.IntegerField(default=0)),
                (
                    "max_value",
                    models.IntegerField(
                        blank=True,
                        help_text="The maximum value of the sequence (can be null if not set)",
                        null=True,
                    ),
                ),
                (
                    "cycle",
                    models.BooleanField(
                        default=False,
                        help_text="If the sequence is circular (e.g. 1,2,3,4,5,1,2,3,4,5)",
                    ),
                ),
                (
                    "step_size",
                    models.IntegerField(
                        default=1,
                        help_text="The step size of the sequence (e.g. 1,2,3,4,5,6)",
                    ),
                ),
            ],
            options={
                "default_related_name": "graph_sequences",
            },
        ),
        migrations.CreateModel(
            name="HistoricalGraph",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "assignation_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "node_deletion_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="If node deletion is allowed in this graph",
                    ),
                ),
                (
                    "edge_deletion_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="If edge deletion is allowed in this graph",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the entity group", max_length=1000
                    ),
                ),
                (
                    "purl",
                    models.CharField(
                        blank=True,
                        help_text="The name of the entity group",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the entity group",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "age_name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the graph class in the age graph",
                        max_length=1000,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Action-level allow/deny rules evaluated against request context",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical graph",
                "verbose_name_plural": "historical graphs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MaterializedEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="MaterializedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "materialized_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the view was materialized. Newer created or deleted_instances are not part of the view",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time the view was created. Newer created or deleted_instances are not part of the view",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time the view was created. Newer created or deleted_instances are not part of the view",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the model", max_length=1000
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NodeQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key of the query, used for referencing the query in the frontend and for pinning it",
                        max_length=1000,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The query that is used to materialize the graph",
                        max_length=7000,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the materialized graph", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the materialized graph",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="The kind of the materialized graph (i.e path, property, etc.)",
                        max_length=1000,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "node_queries",
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="OntologyReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the ontology reference", max_length=1000
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the protocol", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the protocol",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "plate_children",
                    models.JSONField(
                        default=list,
                        help_text="The steps of the protocol, each step is a dict with the following keys: name, description, event_category, source_entities, target_entities, source_reagents, target_reagents, variables",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScatterPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the scatter plot", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the scatter plot",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "id_column",
                    models.CharField(
                        help_text="The column that assigns the row_id (could be an edge, a node, etc.)",
                        max_length=1000,
                    ),
                ),
                (
                    "x_column",
                    models.CharField(
                        help_text="The column that assigns the x value",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "x_id_column",
                    models.CharField(
                        help_text="The column that assigns the x_id value",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "y_column",
                    models.CharField(
                        help_text="The column that assigns the y value",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "y_id_column",
                    models.CharField(
                        help_text="The column that assigns an ID to the y value",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "color_column",
                    models.CharField(
                        help_text="The column that assigns the color value",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "size_column",
                    models.CharField(
                        help_text="The column that assigns the size value",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "shape_column",
                    models.CharField(
                        help_text="The column that assigns the shape value",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EdgeCategory",
            fields=[
                (
                    "category_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.category",
                    ),
                ),
                (
                    "source_definition",
                    models.JSONField(
                        default=dict,
                        help_text="Filters for the right side of the edge (e.g. which tags the right side should have)",
                        null=True,
                    ),
                ),
                (
                    "target_definition",
                    models.JSONField(
                        default=dict,
                        help_text="Filters for the left side of the edge (e.g. which tags the left side should have)",
                        null=True,
                    ),
                ),
                (
                    "reverse_label",
                    models.CharField(
                        help_text="The reverse label of the edge class",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "property_definitions",
                    models.JSONField(
                        default=list, help_text="The property definitions of this"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.category",),
        ),
        migrations.CreateModel(
            name="NodeCategory",
            fields=[
                (
                    "category_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.category",
                    ),
                ),
                (
                    "schema_hash",
                    models.CharField(
                        default="",
                        help_text="The schema hash representing the version of the schema this category was defined with",
                        max_length=1000,
                    ),
                ),
                (
                    "position_x",
                    models.FloatField(
                        help_text="The x position of the node class in the graph (if a node)",
                        null=True,
                    ),
                ),
                (
                    "position_y",
                    models.FloatField(
                        help_text="The y position of the  node class in the graph (if a node)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        help_text="The height of the  node class in the graph (if a node)",
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        help_text="The width of the  node class in the graph (if a node)",
                        null=True,
                    ),
                ),
                (
                    "property_definitions",
                    models.JSONField(
                        default=list, help_text="The property definitions of this"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.category",),
        ),
    ]
