# Generated by Django 6.0.3 on 2026-08-13 19:45

import core.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datalayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='The value of the tag', max_length=1000)),
                ('name', models.CharField(help_text='The name of the tag', max_length=1000, null=True)),
                ('description', models.CharField(help_text='The description of the tag', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_related_name': 'category_tags',
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The name of the descriptor', max_length=1000)),
                ('description', models.CharField(help_text='The description of the descriptor', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='The value of the descriptor', max_length=1000)),
            ],
            options={
                'default_related_name': 'descriptors',
            },
        ),
        migrations.CreateModel(
            name='EdgeQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key of the query, used for referencing the query in the frontend and for pinning it', max_length=1000)),
                ('query', models.CharField(help_text='The query that is used to materialize the graph', max_length=7000)),
                ('label', models.CharField(help_text='The name of the materialized graph', max_length=1000)),
                ('description', models.CharField(help_text='The description of the materialized graph', max_length=1000, null=True)),
                ('kind', models.CharField(choices=[('PATH', 'Path'), ('PAIRS', 'Pairs'), ('TABLE', 'Table')], help_text='The kind of the materialized graph (i.e path, property, etc.)', max_length=1000)),
                ('columns', models.JSONField(default=list, help_text='The columns (if ViewKind is Table)', null=True)),
            ],
            options={
                'default_related_name': 'edge_queries',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_deletion_allowed', models.BooleanField(default=True, help_text='If node deletion is allowed in this graph')),
                ('edge_deletion_allowed', models.BooleanField(default=True, help_text='If edge deletion is allowed in this graph')),
                ('name', models.CharField(help_text='The name of the entity group', max_length=1000)),
                ('purl', models.CharField(blank=True, help_text='The name of the entity group', max_length=1000, null=True)),
                ('description', models.CharField(help_text='The description of the entity group', max_length=2000, null=True)),
                ('age_name', models.CharField(help_text='The name of the graph class in the age graph', max_length=1000, unique=True)),
                ('rules', models.JSONField(blank=True, default=list, help_text='Action-level allow/deny rules evaluated against request context')),
                ('selector', models.JSONField(blank=True, default=dict, help_text="Declarative definition of which of the organization's evidence this graph projects. A graph is a view now, not a silo: membership is evaluated from this selector into a droppable cache, never maintained on write — otherwise every ingest would have to know about every projection. Shape: {category_keys: [...], assertion_filter: {subjects, app_ids, action_names}, as_of: timestamp, observed_window: [from, to]}. Read in three places, all at projection or read time: which metrics a derived property counts, whose classification claims a defined category admits, and whose existence claims decide whether a node is in this view at all. **Changing it requires a reproject**: the projection is a cache of the answer this selector produced, so editing the selector without rebuilding leaves the graph showing the previous one.")),
            ],
        ),
        migrations.CreateModel(
            name='GraphOntology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the ontology', max_length=1000)),
                ('url', models.CharField(help_text='The URL of the ontology', max_length=2000)),
                ('description', models.CharField(help_text='The description of the ontology', max_length=2000, null=True)),
            ],
            options={
                'default_related_name': 'graph_ontologies',
            },
        ),
        migrations.CreateModel(
            name='GraphQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key of the query, used for referencing the query in the frontend and for pinning it', max_length=1000)),
                ('query', models.CharField(help_text='The query that is used to materialize the graph', max_length=7000)),
                ('label', models.CharField(help_text='The name of the materialized graph', max_length=1000)),
                ('description', models.CharField(help_text='The description of the materialized graph', max_length=1000, null=True)),
                ('kind', models.CharField(choices=[('NODES', 'Nodes'), ('PATH', 'Path'), ('PAIRS', 'Pairs'), ('TABLE', 'Table')], help_text='The kind of the materialized graph (i.e path, property, etc.)', max_length=1000)),
                ('returns', models.JSONField(default=list, help_text='The returns of the query', null=True)),
                ('matches', models.JSONField(default=list, help_text='The matches of the query', null=True)),
                ('wheres', models.JSONField(default=list, help_text='The wheres of the query', null=True)),
                ('columns', models.JSONField(default=list, help_text='The columns (if ViewKind is Table)', null=True)),
            ],
            options={
                'default_related_name': 'graph_queries',
            },
        ),
        migrations.CreateModel(
            name='GraphSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Semantic version of this schema (e.g., '1.0.0')", max_length=100)),
                ('index', models.PositiveIntegerField(help_text='Sequential index of this schema version (auto-incremented)')),
                ('definition', models.JSONField(help_text='The full GraphDefinitionModel as JSON')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active schema for the graph')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Description of changes in this schema version', null=True)),
                ('hash', models.CharField(db_index=True, default='', help_text="Content hash of `definition`. This is the identity a projected node stamps as its `__schema_version`, so a derived value can be told apart from one computed under an older schema. Distinct from `NodeCategory.schema_hash`, which hashes one category's properties rather than the whole graph definition.", max_length=64)),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='GraphSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(help_text='The index name that was created', max_length=1000)),
                ('label', models.CharField(help_text='The label of the sequence', max_length=1000, null=True)),
                ('description', models.CharField(help_text='The description of the sequence', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_value', models.IntegerField(default=0)),
                ('start_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(blank=True, help_text='The maximum value of the sequence (can be null if not set)', null=True)),
                ('cycle', models.BooleanField(default=False, help_text='If the sequence is circular (e.g. 1,2,3,4,5,1,2,3,4,5)')),
                ('step_size', models.IntegerField(default=1, help_text='The step size of the sequence (e.g. 1,2,3,4,5,6)')),
            ],
            options={
                'default_related_name': 'graph_sequences',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGraph',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('node_deletion_allowed', models.BooleanField(default=True, help_text='If node deletion is allowed in this graph')),
                ('edge_deletion_allowed', models.BooleanField(default=True, help_text='If edge deletion is allowed in this graph')),
                ('name', models.CharField(help_text='The name of the entity group', max_length=1000)),
                ('purl', models.CharField(blank=True, help_text='The name of the entity group', max_length=1000, null=True)),
                ('description', models.CharField(help_text='The description of the entity group', max_length=2000, null=True)),
                ('age_name', models.CharField(db_index=True, help_text='The name of the graph class in the age graph', max_length=1000)),
                ('rules', models.JSONField(blank=True, default=list, help_text='Action-level allow/deny rules evaluated against request context')),
                ('selector', models.JSONField(blank=True, default=dict, help_text="Declarative definition of which of the organization's evidence this graph projects. A graph is a view now, not a silo: membership is evaluated from this selector into a droppable cache, never maintained on write — otherwise every ingest would have to know about every projection. Shape: {category_keys: [...], assertion_filter: {subjects, app_ids, action_names}, as_of: timestamp, observed_window: [from, to]}. Read in three places, all at projection or read time: which metrics a derived property counts, whose classification claims a defined category admits, and whose existence claims decide whether a node is in this view at all. **Changing it requires a reproject**: the projection is a cache of the answer this selector produced, so editing the selector without rebuilding leaves the graph showing the previous one.")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical graph',
                'verbose_name_plural': 'historical graphs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MaterializedEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RELATION', 'Relation'), ('MEASUREMENT', 'Measurement'), ('STRUCTURE_RELATION', 'Structure Relation')], help_text='Which kind of category this edge was derived from', max_length=1000)),
                ('role', models.CharField(blank=True, help_text='The role of the edge, if its part of a protocol or natural event (e.g. source, target, etc.)', max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialized_at', models.DateTimeField(auto_now_add=True, help_text='The time the view was materialized. Newer created or deleted_instances are not part of the view')),
                ('valid_from', models.DateTimeField(blank=True, help_text='The time the view was created. Newer created or deleted_instances are not part of the view', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='The time the view was created. Newer created or deleted_instances are not part of the view', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the model', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NodeQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key of the query, used for referencing the query in the frontend and for pinning it', max_length=1000)),
                ('query', models.CharField(help_text='The query that is used to materialize the graph', max_length=7000)),
                ('label', models.CharField(help_text='The name of the materialized graph', max_length=1000)),
                ('description', models.CharField(help_text='The description of the materialized graph', max_length=1000, null=True)),
                ('kind', models.CharField(choices=[('PATH', 'Path'), ('PAIRS', 'Pairs'), ('TABLE', 'Table')], help_text='The kind of the materialized graph (i.e path, property, etc.)', max_length=1000)),
                ('columns', models.JSONField(default=list, help_text='The columns (if ViewKind is Table)', null=True)),
            ],
            options={
                'default_related_name': 'node_queries',
            },
        ),
        migrations.CreateModel(
            name='OntologyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the ontology reference', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the protocol', max_length=1000)),
                ('description', models.CharField(help_text='The description of the protocol', max_length=2000, null=True)),
                ('plate_children', models.JSONField(default=list, help_text='The steps of the protocol, each step is a dict with the following keys: name, description, event_category, source_entities, target_entities, source_reagents, target_reagents, variables')),
            ],
        ),
        migrations.CreateModel(
            name='ScatterPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the scatter plot', max_length=1000)),
                ('description', models.CharField(help_text='The description of the scatter plot', max_length=1000, null=True)),
                ('id_column', models.CharField(help_text='The column that assigns the row_id (could be an edge, a node, etc.)', max_length=1000)),
                ('x_column', models.CharField(help_text='The column that assigns the x value', max_length=1000, null=True)),
                ('x_id_column', models.CharField(help_text='The column that assigns the x_id value', max_length=1000, null=True)),
                ('y_column', models.CharField(help_text='The column that assigns the y value', max_length=1000, null=True)),
                ('y_id_column', models.CharField(help_text='The column that assigns an ID to the y value', max_length=1000, null=True)),
                ('color_column', models.CharField(help_text='The column that assigns the color value', max_length=1000, null=True)),
                ('size_column', models.CharField(help_text='The column that assigns the size value', max_length=1000, null=True)),
                ('shape_column', models.CharField(help_text='The column that assigns the shape value', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ENTITY', 'Entity'), ('REAGENT', 'Reagent'), ('NATURAL_EVENT', 'Natural Event'), ('PROTOCOL_EVENT', 'Protocol Event'), ('MEASUREMENT', 'Measurement'), ('RELATION', 'Relation'), ('STRUCTURE_RELATION', 'Structure Relation')], help_text='Which kind of category this is, and therefore which of the kind-specific fields below are meaningful', max_length=1000)),
                ('age_name', models.CharField(help_text='The name of the graph class in the age graph', max_length=1000)),
                ('key', models.CharField(help_text='The entity key that the node relates to (e.g. a cell line, a cell type, etc.)', max_length=1000)),
                ('description', models.CharField(help_text='The description of category', max_length=1000, null=True)),
                ('purl', models.CharField(help_text='The PURL (Persistent Uniform Resource Locator)', max_length=1000, null=True)),
                ('definition', models.JSONField(blank=True, default=dict, help_text="What this category *means in this graph*, as a predicate over classification claims. Empty means primitive: membership is whatever was asserted, which is the default and the old behaviour. Non-empty makes it a defined category — necessary and sufficient conditions, evaluated at projection time, so 'AIS' can mean 'asserted AIS by Johannes before August' in one graph and something else in another without touching a single piece of evidence. Shape: {asserted_as: <category key>, assertion_filter: {subjects, app_ids, action_names}, as_of: timestamp}. See `evidence.selector.classification_filter`.")),
                ('color', models.JSONField(default=core.models.random_color, help_text='The color of the entity class as RGB', max_length=1000, null=True)),
                ('label', models.CharField(help_text='The label of the node class', max_length=1000, null=True)),
                ('ports', models.JSONField(default=list, help_text='The ports of the node class ssin the graph (if a node)', null=True)),
                ('schema_hash', models.CharField(default='', help_text='The schema hash representing the version of the schema this category was defined with', max_length=1000)),
                ('position_x', models.FloatField(help_text='The x position of the node class in the graph (if a node)', null=True)),
                ('position_y', models.FloatField(help_text='The y position of the  node class in the graph (if a node)', null=True)),
                ('height', models.FloatField(help_text='The height of the  node class in the graph (if a node)', null=True)),
                ('width', models.FloatField(help_text='The width of the  node class in the graph (if a node)', null=True)),
                ('property_definitions', models.JSONField(default=list, help_text='The property definitions of this')),
                ('source_definition', models.JSONField(default=dict, help_text='Filters for the right side of the edge (e.g. which tags the right side should have)', null=True)),
                ('target_definition', models.JSONField(default=dict, help_text='Filters for the left side of the edge (e.g. which tags the left side should have)', null=True)),
                ('reverse_label', models.CharField(help_text='The reverse label of the edge class', max_length=1000, null=True)),
                ('instance_kind', models.CharField(blank=True, help_text='What an instance of this class represents (e.g. a LOT, an object, etc.). Entity and reagent categories only', max_length=1000, null=True)),
                ('reverse_description', models.CharField(help_text='The description of category read in reverse. Relation and structure-relation categories only', max_length=1000, null=True)),
                ('source_entity_roles', models.JSONField(default=list, help_text='The categories or expressions that an event of this class can source from (source edges). Event categories only', null=True)),
                ('target_entity_roles', models.JSONField(default=list, help_text='The categories or expressions that an of this class can target to (target edges). Event categories only', null=True)),
                ('source_reagent_roles', models.JSONField(default=list, help_text='The reagent categories an event of this class can source from. Protocol event categories only', null=True)),
                ('target_reagent_roles', models.JSONField(default=list, help_text='The reagent categories an event of this class can target. Protocol event categories only', null=True)),
                ('variable_definitions', models.JSONField(default=list, help_text='The variables of a instance this protocol event will needs (properties on the node). Protocol event categories only', null=True)),
                ('plate_children', models.JSONField(blank=True, help_text='Event categories only', null=True)),
                ('image', models.ForeignKey(blank=True, help_text='The store of the image if associated with the category', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.mediastore')),
                ('pinned_by', models.ManyToManyField(help_text='The users that have this query active', related_name='pinned_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'categories',
            },
        ),
    ]
