# Generated by Django 5.2 on 2025-11-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphquery',
            name='matches',
            field=models.JSONField(default=list, help_text='The matches of the query', null=True),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='returns',
            field=models.JSONField(default=list, help_text='The returns of the query', null=True),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='wheres',
            field=models.JSONField(default=list, help_text='The wheres of the query', null=True),
        ),
    ]
