# Generated by Django 4.2.8 on 2025-02-19 11:33

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodequery",
            name="kind",
            field=models.CharField(
                default="PATH",
                help_text="The kind of the materialized graph (i.e path, property, etc.)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="s3store",
            name="path",
            field=core.fields.S3Field(
                blank=True,
                help_text="The stodre of the image",
                max_length=500,
                null=True,
                unique=True,
            ),
        ),
    ]
