# Generated by Django 5.2 on 2025-07-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureRelationCategory',
            fields=[
                ('edgecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.edgecategory')),
                ('label', models.CharField(help_text='How this step acts in the protocol (e.g. as which reagent)', max_length=1000, null=True)),
            ],
            options={
                'default_related_name': 'structure_relation_categories',
            },
            bases=('core.edgecategory',),
        ),
    ]
