# Generated by Django 5.2 on 2026-02-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="graph",
            old_name="store",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="historicalgraph",
            old_name="store",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="graphquery",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this query belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to="core.graph",
            ),
        ),
    ]
