# Generated by Django 5.2 on 2025-09-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='edge_deletion_allowed',
            field=models.BooleanField(default=True, help_text='If node deletion is allowed in this graph'),
        ),
        migrations.AddField(
            model_name='graph',
            name='node_deletion_allowed',
            field=models.BooleanField(default=True, help_text='If node deletion is allowed in this graph'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='edge_deletion_allowed',
            field=models.BooleanField(default=True, help_text='If node deletion is allowed in this graph'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='node_deletion_allowed',
            field=models.BooleanField(default=True, help_text='If node deletion is allowed in this graph'),
        ),
    ]
