# Generated by Django 5.2 on 2026-03-16 12:30

import core.enums
import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentikate", "0005_alter_client_client_id"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        ("datalayer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="The store of the image if associated with the category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datalayer.mediastore",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="The tags of the category", to="core.categorytag"
            ),
        ),
        migrations.AddField(
            model_name="descriptor",
            name="category",
            field=models.ForeignKey(
                help_text="The category this descriptor belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptors",
                to="core.category",
            ),
        ),
        migrations.CreateModel(
            name="EdgePairsQuery",
            fields=[
                (
                    "edgequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgequery",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.edgequery",),
        ),
        migrations.CreateModel(
            name="EdgePathQuery",
            fields=[
                (
                    "edgequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgequery",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.edgequery",),
        ),
        migrations.CreateModel(
            name="EdgeTableQuery",
            fields=[
                (
                    "edgequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgequery",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="The columns (if ViewKind is Table)",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.edgequery",),
        ),
        migrations.AddField(
            model_name="edgequery",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_edge_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="edgequery",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="The store of the image if associated with the category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datalayer.mediastore",
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphs",
                to="authentikate.membership",
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphs",
                to="authentikate.organization",
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_graphs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="user",
            field=models.ForeignKey(
                help_text="The user that this graph belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="edgequery",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this query belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edge_queries",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="categorytag",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this tag belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_tags",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.graph"
            ),
        ),
        migrations.CreateModel(
            name="GraphTableQuery",
            fields=[
                (
                    "graphquery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.graphquery",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="The columns (if ViewKind is Table)",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.graphquery",),
        ),
        migrations.AddField(
            model_name="graphquery",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this query belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="graphquery",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_graph_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graphquery",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="graphquery",
            name="relevant_for",
            field=models.ManyToManyField(
                help_text="The expression that this query should be mostly used for",
                related_name="relevant_graph_queries",
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="graphontology",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this ontology belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ontologies",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="graphschema",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this schema",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_schemas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graphschema",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this schema belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schemas",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="graphsequence",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this sequence belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_sequences",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                help_text="The index of this category (new entities will be created with this index)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.graphsequence",
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentikate.client",
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="provenance_entries",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="image",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The store of the image if associated with the category",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="datalayer.mediastore",
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="authentikate.membership",
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="authentikate.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The user that this graph belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materializededge",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this edge belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materialized_edges",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="materializededge",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="materializedview",
            name="creator",
            field=models.ForeignKey(
                help_text="The user that created the view",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materializedview",
            name="query",
            field=models.ForeignKey(
                help_text="The query that is used to materialize the graph",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="core.graphquery",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="materialized_graph",
            field=models.ForeignKey(
                blank=True,
                help_text="The materialized grpah this model was trained on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="core.materializedview",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="The store of the model",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="datalayer.mediastore",
            ),
        ),
        migrations.CreateModel(
            name="NodePairsQuery",
            fields=[
                (
                    "nodequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodequery",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.nodequery",),
        ),
        migrations.CreateModel(
            name="NodePathQuery",
            fields=[
                (
                    "nodequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodequery",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.nodequery",),
        ),
        migrations.CreateModel(
            name="NodeTableQuery",
            fields=[
                (
                    "nodequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodequery",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="The columns (if ViewKind is Table)",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.nodequery",),
        ),
        migrations.AddField(
            model_name="nodequery",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this query belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node_queries",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="nodequery",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_node_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nodequery",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="ontologyreference",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ontology_references",
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="ontologyreference",
            name="ontology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="core.graphontology",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="graph",
            field=models.ForeignKey(
                help_text="The graph this protocol belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to="core.graph",
            ),
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="creator",
            field=models.ForeignKey(
                help_text="The user that created the scatter plot",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MeasurementCategory",
            fields=[
                (
                    "edgecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgecategory",
                    ),
                ),
            ],
            options={
                "default_related_name": "measurement_categories",
            },
            bases=("core.edgecategory",),
        ),
        migrations.CreateModel(
            name="RelationCategory",
            fields=[
                (
                    "edgecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgecategory",
                    ),
                ),
                (
                    "reverse_description",
                    models.CharField(
                        help_text="The description of category",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "default_related_name": "relation_categories",
            },
            bases=("core.edgecategory",),
        ),
        migrations.CreateModel(
            name="StructureRelationCategory",
            fields=[
                (
                    "edgecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgecategory",
                    ),
                ),
                (
                    "reverse_description",
                    models.CharField(
                        help_text="The description of category",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "default_related_name": "structure_relation_categories",
            },
            bases=("core.edgecategory",),
        ),
        migrations.AddField(
            model_name="edgequery",
            name="relevant_for_edges",
            field=models.ManyToManyField(
                help_text="The entities that this query should be mostly used for",
                related_name="relevant_edge_queries",
                to="core.edgecategory",
            ),
        ),
        migrations.CreateModel(
            name="EntityCategory",
            fields=[
                (
                    "nodecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodecategory",
                    ),
                ),
                (
                    "instance_kind",
                    models.CharField(
                        blank=True,
                        help_text="What an instance of this class represents (e.g. a LOT, an object, etc.)",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "default_related_name": "entity_categories",
            },
            bases=("core.nodecategory",),
        ),
        migrations.CreateModel(
            name="NaturalEventCategory",
            fields=[
                (
                    "nodecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodecategory",
                    ),
                ),
                (
                    "source_entity_roles",
                    models.JSONField(
                        default=list,
                        help_text="The categories or expressions that an event of this class can source from (source edges)",
                    ),
                ),
                (
                    "target_entity_roles",
                    models.JSONField(
                        default=list,
                        help_text="The categories or expressions that an of this class can target to (target edges)",
                    ),
                ),
                ("plate_children", models.JSONField(blank=True, null=True)),
            ],
            options={
                "default_related_name": "natural_event_categories",
            },
            bases=("core.nodecategory",),
        ),
        migrations.CreateModel(
            name="ProtocolEventCategory",
            fields=[
                (
                    "nodecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodecategory",
                    ),
                ),
                (
                    "source_entity_roles",
                    models.JSONField(
                        default=list,
                        help_text="The categories or expressions that an event of this class can source from (source edges)",
                    ),
                ),
                (
                    "target_entity_roles",
                    models.JSONField(
                        default=list,
                        help_text="The categories or expressions that an of this class can target to (target edges)",
                    ),
                ),
                (
                    "source_reagent_roles",
                    models.JSONField(
                        default=list,
                        help_text="The categories or expressions that an event of this class can source from (source edges)",
                    ),
                ),
                (
                    "target_reagent_roles",
                    models.JSONField(
                        default=list,
                        help_text="The categories or expressions that an of this class can target to (target edges)",
                    ),
                ),
                (
                    "variable_definitions",
                    models.JSONField(
                        default=list,
                        help_text="The variables of a instance this protocol event will needs (properties on the node)",
                    ),
                ),
                ("plate_children", models.JSONField(blank=True, null=True)),
            ],
            options={
                "default_related_name": "protocol_event_categories",
            },
            bases=("core.nodecategory",),
        ),
        migrations.CreateModel(
            name="ReagentCategory",
            fields=[
                (
                    "nodecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodecategory",
                    ),
                ),
                (
                    "instance_kind",
                    models.CharField(
                        blank=True,
                        help_text="What an instance of this class represents (e.g. a LOT, an object, etc.)",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "default_related_name": "reagent_categories",
            },
            bases=("core.nodecategory",),
        ),
        migrations.CreateModel(
            name="StructureCategory",
            fields=[
                (
                    "nodecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodecategory",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="The structure identifier that the node relates to",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "default_related_name": "structure_categories",
            },
            bases=("core.nodecategory",),
        ),
        migrations.AddField(
            model_name="nodequery",
            name="relevant_for_nodes",
            field=models.ManyToManyField(
                help_text="The entities that this query should be mostly used for",
                related_name="relevant_node_queries",
                to="core.nodecategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="descriptor",
            unique_together={("category", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="categorytag",
            unique_together={("graph", "value")},
        ),
        migrations.CreateModel(
            name="GraphNodesQuery",
            fields=[
                (
                    "graphquery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.graphquery",
                    ),
                ),
                (
                    "node_category",
                    models.ForeignKey(
                        default=None,
                        help_text="The category this query is associated if its a node_list",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_list_queries",
                        to="core.nodecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.graphquery",),
        ),
        migrations.CreateModel(
            name="GraphPairsQuery",
            fields=[
                (
                    "graphquery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.graphquery",
                    ),
                ),
                (
                    "left_category",
                    models.ForeignKey(
                        default=None,
                        help_text="The category this query is associated if its a path_list",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_left_queries",
                        to="core.nodecategory",
                    ),
                ),
                (
                    "right_category",
                    models.ForeignKey(
                        default=None,
                        help_text="The category this query is associated if its a path_list",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_right_queries",
                        to="core.nodecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.graphquery",),
        ),
        migrations.CreateModel(
            name="GraphPathQuery",
            fields=[
                (
                    "graphquery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.graphquery",
                    ),
                ),
                (
                    "left_category",
                    models.ForeignKey(
                        default=None,
                        help_text="The category this query is associated if its a path_list",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_list_queries",
                        to="core.nodecategory",
                    ),
                ),
                (
                    "right_category",
                    models.ForeignKey(
                        default=None,
                        help_text="The category this query is associated if its a path_list",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_list_queries_right",
                        to="core.nodecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.graphquery",),
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="graph_query",
            field=models.ForeignKey(
                blank=True,
                help_text="The query this scatter plot was trained on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to="core.graphtablequery",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="graphquery",
            unique_together={("graph", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="graphontology",
            unique_together={("graph", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="graphschema",
            unique_together={("graph", "index"), ("graph", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="graphsequence",
            unique_together={("graph", "index")},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("graph", "age_name"), ("graph", "key")},
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="path_query",
            field=models.ForeignKey(
                blank=True,
                help_text="The path query this scatter plot was trained on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to="core.nodepathquery",
            ),
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="node_query",
            field=models.ForeignKey(
                blank=True,
                help_text="The node query this scatter plot was trained on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to="core.nodetablequery",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="edgequery",
            unique_together={("graph", "key")},
        ),
        migrations.CreateModel(
            name="MaterializedRelationEdge",
            fields=[
                (
                    "materializededge_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.materializededge",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="The role of the edge, if its part of a protocol or natural event (e.g. source, target, etc.)",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        db_column="relation_id",
                        help_text="The relation category of the edge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materialized_relation_edges_as_relation",
                        to="core.relationcategory",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source category of the edge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materialized_relation_edges_as_source",
                        to="core.entitycategory",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The target category of the edge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materialized_relation_edges_as_target",
                        to="core.entitycategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.materializededge",),
        ),
        migrations.CreateModel(
            name="MetricCategory",
            fields=[
                (
                    "nodecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodecategory",
                    ),
                ),
                (
                    "value_kind",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("INT", "Int"),
                            ("FLOAT", "Float"),
                            ("DATETIME", "Datetime"),
                            ("STRING", "String"),
                            ("CATEGORY", "Category"),
                            ("BOOLEAN", "Boolean"),
                            ("THREE_D_VECTOR", "Three D Vector"),
                            ("TWO_D_VECTOR", "Two D Vector"),
                            ("ONE_D_VECTOR", "One D Vector"),
                            ("FOUR_D_VECTOR", "Four D Vector"),
                            ("N_VECTOR", "N Vector"),
                        ],
                        choices_enum=core.enums.MetricKindChoices,
                        help_text="The data type (if a metric)",
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    "structure_category",
                    models.ForeignKey(
                        help_text="The structure category that this metric describes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_categories",
                        to="core.structurecategory",
                    ),
                ),
            ],
            options={
                "default_related_name": "metric_categories",
            },
            bases=("core.nodecategory",),
        ),
        migrations.CreateModel(
            name="MaterializedStructureRelationEdge",
            fields=[
                (
                    "materializededge_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.materializededge",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="The role of the edge, if its part of a protocol or natural event (e.g. source, target, etc.)",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        db_column="relation_id",
                        help_text="The relation category of the edge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materialized_structure_relation_edges_as_relation",
                        to="core.structurerelationcategory",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source category of the edge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materialized_structure_relation_edges_as_source",
                        to="core.structurecategory",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The target category of the edge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materialized_structure_relation_edges_as_target",
                        to="core.structurecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.materializededge",),
        ),
        migrations.AlterUniqueTogether(
            name="nodequery",
            unique_together={("graph", "key")},
        ),
    ]
