# Generated by Django 4.2.8 on 2025-02-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="left",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="left_edges",
                to="core.expression",
            ),
        ),
        migrations.AddField(
            model_name="expression",
            name="right",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="right_edges",
                to="core.expression",
            ),
        ),
    ]
