# Generated by Django 4.2.8 on 2024-11-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="The store of the model",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="core.mediastore",
            ),
        ),
    ]
