# Generated by Django 6.0.3 on 2026-08-13 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0001_initial'),
        ('datalayer', '0001_initial'),
        ('evidence', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='term',
            field=models.ForeignKey(blank=True, help_text="The organization's word this category declares. **This row is what the term means *here*** — its label in Apache AGE, its `definition`, its derivation rules and its layout are all properties of this graph. The term is the part every view shares, and the part the evidence log names, so one annotator's claim can be read by a graph that did not make it. `PROTECT` because a word that has been used has to outlive the views that used it; deleting *this* row is free, and only drops the term from this graph.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='evidence.term'),
        ),
        migrations.CreateModel(
            name='EdgeCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.category',),
        ),
        migrations.CreateModel(
            name='NodeCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.category',),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags of the category', to='core.categorytag'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='category',
            field=models.ForeignKey(help_text='The category this descriptor belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='core.category'),
        ),
        migrations.AddField(
            model_name='edgequery',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have this query active', related_name='pinned_edge_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EdgePairsQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.edgequery',),
        ),
        migrations.CreateModel(
            name='EdgePathQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.edgequery',),
        ),
        migrations.CreateModel(
            name='EdgeTableQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.edgequery',),
        ),
        migrations.AddField(
            model_name='graph',
            name='image',
            field=models.ForeignKey(blank=True, help_text='The store of the image if associated with the category', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.mediastore'),
        ),
        migrations.AddField(
            model_name='graph',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='graph',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='graph',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have this query active', related_name='pinned_graphs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graph',
            name='user',
            field=models.ForeignKey(help_text='The user that this graph belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edgequery',
            name='graph',
            field=models.ForeignKey(help_text='The graph this query belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='edge_queries', to='core.graph'),
        ),
        migrations.AddField(
            model_name='categorytag',
            name='graph',
            field=models.ForeignKey(help_text='The graph this tag belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='category_tags', to='core.graph'),
        ),
        migrations.AddField(
            model_name='category',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph'),
        ),
        migrations.AddField(
            model_name='graphontology',
            name='graph',
            field=models.ForeignKey(help_text='The graph this ontology belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ontologies', to='core.graph'),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='graph',
            field=models.ForeignKey(help_text='The graph this query belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.graph'),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have this query active', related_name='pinned_graph_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='relevant_for',
            field=models.ManyToManyField(help_text='The expression that this query should be mostly used for', related_name='relevant_graph_queries', to='core.category'),
        ),
        migrations.CreateModel(
            name='GraphNodesQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.graphquery',),
        ),
        migrations.CreateModel(
            name='GraphPairsQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.graphquery',),
        ),
        migrations.CreateModel(
            name='GraphPathQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.graphquery',),
        ),
        migrations.CreateModel(
            name='GraphTableQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.graphquery',),
        ),
        migrations.AddField(
            model_name='graphschema',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this schema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graphschema',
            name='graph',
            field=models.ForeignKey(help_text='The graph this schema belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='core.graph'),
        ),
        migrations.AddField(
            model_name='graphsequence',
            name='graph',
            field=models.ForeignKey(help_text='The graph this sequence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graph_sequences', to='core.graph'),
        ),
        migrations.AddField(
            model_name='category',
            name='sequence',
            field=models.ForeignKey(blank=True, help_text='The index of this category (new entities will be created with this index)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.graphsequence'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.graph'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The store of the image if associated with the category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.mediastore'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='membership',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that this graph belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materializededge',
            name='edge_category',
            field=models.ForeignKey(help_text='The edge category this edge was derived from', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_edge', to='core.category'),
        ),
        migrations.AddField(
            model_name='materializededge',
            name='graph',
            field=models.ForeignKey(help_text='The graph this edge belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges', to='core.graph'),
        ),
        migrations.AddField(
            model_name='materializededge',
            name='source_category',
            field=models.ForeignKey(blank=True, help_text='The source category of the edge, for relation edges', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_source', to='core.category'),
        ),
        migrations.AddField(
            model_name='materializededge',
            name='source_structure_kind',
            field=models.ForeignKey(blank=True, help_text='The source structure kind of the edge, for measurement and structure-relation edges', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_source', to='evidence.structurekind'),
        ),
        migrations.AddField(
            model_name='materializededge',
            name='target_category',
            field=models.ForeignKey(blank=True, help_text='The target category of the edge, for relation and measurement edges', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_target', to='core.category'),
        ),
        migrations.AddField(
            model_name='materializededge',
            name='target_structure_kind',
            field=models.ForeignKey(blank=True, help_text='The target structure kind of the edge, for structure-relation edges', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_target', to='evidence.structurekind'),
        ),
        migrations.CreateModel(
            name='MaterializedMeasurementEdge',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.materializededge',),
        ),
        migrations.CreateModel(
            name='MaterializedRelationEdge',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.materializededge',),
        ),
        migrations.CreateModel(
            name='MaterializedStructureRelationEdge',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.materializededge',),
        ),
        migrations.AddField(
            model_name='materializedview',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the view', on_delete=django.db.models.deletion.CASCADE, related_name='graph_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materializedview',
            name='query',
            field=models.ForeignKey(help_text='The query that is used to materialize the graph', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.graphquery'),
        ),
        migrations.AddField(
            model_name='model',
            name='materialized_graph',
            field=models.ForeignKey(blank=True, help_text='The materialized grpah this model was trained on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.materializedview'),
        ),
        migrations.AddField(
            model_name='model',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store of the model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='datalayer.mediastore'),
        ),
        migrations.AddField(
            model_name='nodequery',
            name='graph',
            field=models.ForeignKey(help_text='The graph this query belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='node_queries', to='core.graph'),
        ),
        migrations.AddField(
            model_name='nodequery',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have this query active', related_name='pinned_node_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NodePairsQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.nodequery',),
        ),
        migrations.CreateModel(
            name='NodePathQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.nodequery',),
        ),
        migrations.CreateModel(
            name='NodeTableQuery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.nodequery',),
        ),
        migrations.AddField(
            model_name='ontologyreference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_references', to='core.category'),
        ),
        migrations.AddField(
            model_name='ontologyreference',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.graphontology'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='graph',
            field=models.ForeignKey(help_text='The graph this protocol belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='core.graph'),
        ),
        migrations.AddField(
            model_name='scatterplot',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the scatter plot', on_delete=django.db.models.deletion.CASCADE, related_name='scatter_plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edgequery',
            name='relevant_for_edges',
            field=models.ManyToManyField(help_text='The entities that this query should be mostly used for', related_name='relevant_edge_queries', to='core.edgecategory'),
        ),
        migrations.CreateModel(
            name='MeasurementCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.edgecategory',),
        ),
        migrations.CreateModel(
            name='RelationCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.edgecategory',),
        ),
        migrations.CreateModel(
            name='StructureRelationCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.edgecategory',),
        ),
        migrations.AddField(
            model_name='nodequery',
            name='relevant_for_nodes',
            field=models.ManyToManyField(help_text='The entities that this query should be mostly used for', related_name='relevant_node_queries', to='core.nodecategory'),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='left_category',
            field=models.ForeignKey(default=None, help_text='The category this query starts from, if it is a path or pairs query', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_graph_queries', to='core.nodecategory'),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='node_category',
            field=models.ForeignKey(default=None, help_text='The category this query is associated if its a node_list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_list_queries', to='core.nodecategory'),
        ),
        migrations.AddField(
            model_name='graphquery',
            name='right_category',
            field=models.ForeignKey(default=None, help_text='The category this query ends at, if it is a path or pairs query', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_graph_queries', to='core.nodecategory'),
        ),
        migrations.CreateModel(
            name='EntityCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.nodecategory',),
        ),
        migrations.CreateModel(
            name='NaturalEventCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.nodecategory',),
        ),
        migrations.CreateModel(
            name='ProtocolEventCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.nodecategory',),
        ),
        migrations.CreateModel(
            name='ReagentCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.nodecategory',),
        ),
        migrations.AlterUniqueTogether(
            name='descriptor',
            unique_together={('category', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytag',
            unique_together={('graph', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='graphontology',
            unique_together={('graph', 'name')},
        ),
        migrations.AddField(
            model_name='scatterplot',
            name='graph_query',
            field=models.ForeignKey(blank=True, help_text='The query this scatter plot was trained on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scatter_plots', to='core.graphtablequery'),
        ),
        migrations.AddConstraint(
            model_name='graphschema',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('graph',), name='one_active_schema_per_graph'),
        ),
        migrations.AlterUniqueTogether(
            name='graphschema',
            unique_together={('graph', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='graphsequence',
            unique_together={('graph', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('graph', 'age_name'), ('graph', 'key')},
        ),
        migrations.AddField(
            model_name='scatterplot',
            name='path_query',
            field=models.ForeignKey(blank=True, help_text='The path query this scatter plot was trained on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_path_scatter_plots', to='core.nodepathquery'),
        ),
        migrations.AddField(
            model_name='scatterplot',
            name='node_query',
            field=models.ForeignKey(blank=True, help_text='The node query this scatter plot was trained on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_table_scatter_plots', to='core.nodetablequery'),
        ),
        migrations.AlterUniqueTogether(
            name='edgequery',
            unique_together={('graph', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='nodequery',
            unique_together={('graph', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='graphquery',
            unique_together={('graph', 'key')},
        ),
    ]
