# Generated by Django 4.2.8 on 2025-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0002_rename_source_definitions_naturaleventcategory_source_entity_roles_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="naturaleventcategory",
            name="plate_children",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
