# Generated by Django 5.2 on 2025-08-28 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_structurerelationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytag',
            name='graph',
            field=models.ForeignKey(default=1, help_text='The graph this tag belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='category_tags', to='core.graph'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorytag',
            name='name',
            field=models.CharField(help_text='The name of the tag', max_length=1000, null=True),
        ),
    ]
