# Generated by Django 5.2 on 2026-02-14 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_graph_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgeQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The query that is used to materialize the graph",
                        max_length=7000,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the materialized graph", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the materialized graph",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="The kind of the materialized graph (i.e path, property, etc.)",
                        max_length=1000,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="The graph this query belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edge_queries",
                        to="core.graph",
                    ),
                ),
                (
                    "pinned_by",
                    models.ManyToManyField(
                        help_text="The users that have this query active",
                        related_name="pinned_edge_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "relevant_for_edges",
                    models.ManyToManyField(
                        help_text="The entities that this query should be mostly used for",
                        related_name="relevant_edge_queries",
                        to="core.edgecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="nodequery",
            name="relevant_for_nodes",
            field=models.ManyToManyField(
                help_text="The entities that this query should be mostly used for",
                related_name="relevant_node_queries",
                to="core.nodecategory",
            ),
        ),
        migrations.AlterField(
            model_name="scatterplot",
            name="query",
            field=models.ForeignKey(
                help_text="The query this scatter plot was trained on",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to="core.graphtablequery",
            ),
        ),
        migrations.CreateModel(
            name="EdgePathQuery",
            fields=[
                (
                    "edgequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgequery",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.edgequery",),
        ),
        migrations.CreateModel(
            name="EdgeTableQuery",
            fields=[
                (
                    "edgequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgequery",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="The columns (if ViewKind is Table)",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.edgequery",),
        ),
        migrations.CreateModel(
            name="GraphPairsQuery",
            fields=[
                (
                    "graphquery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.graphquery",
                    ),
                ),
                (
                    "left_category",
                    models.ForeignKey(
                        default=None,
                        help_text="The category this query is associated if its a path_list",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_left_queries",
                        to="core.nodecategory",
                    ),
                ),
                (
                    "right_category",
                    models.ForeignKey(
                        default=None,
                        help_text="The category this query is associated if its a path_list",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_right_queries",
                        to="core.nodecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.graphquery",),
        ),
    ]
