# Generated by Django 6.0.3 on 2026-05-19 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedMeasurementEdge',
            fields=[
                ('materializededge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.materializededge')),
                ('edge', models.ForeignKey(db_column='measurement_id', help_text='The measurement category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_measurement_edges_as_measurement', to='core.measurementcategory')),
                ('source', models.ForeignKey(help_text='The source category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_measurement_edges_as_source', to='core.structurecategory')),
                ('target', models.ForeignKey(help_text='The target category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_measurement_edges_as_target', to='core.entitycategory')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.materializededge',),
        ),
    ]
