# Generated by Django 4.2.8 on 2025-02-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_expression_left_expression_right"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="ontology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.ontology"
            ),
        ),
    ]
