# Generated by Django 4.2.8 on 2025-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_nodequery_kind_alter_s3store_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphquery",
            name="columns",
            field=models.JSONField(
                default=None, help_text="The columns (if ViewKind is Table)", null=True
            ),
        ),
        migrations.AddField(
            model_name="nodequery",
            name="columns",
            field=models.JSONField(
                default=None, help_text="The columns (if ViewKind is Table)", null=True
            ),
        ),
    ]
