# Generated by Django 5.2 on 2026-02-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_store_graph_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="store",
            new_name="image",
        ),
    ]
