# Generated by Django 5.2 on 2025-11-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_graphquery_matches_graphquery_returns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitycategory',
            name='variable_definitions',
            field=models.JSONField(default=list, help_text='The variable definitions of this'),
        ),
    ]
