# Generated by Django 6.0.3 on 2026-06-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_materializedmeasurementedge'),
        ('koherent', '0003_rename_assignation_to_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgraph',
            name='assignation_id',
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
    ]
