# Generated by Django 5.2 on 2025-09-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorytag_graph_categorytag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgecategory',
            name='reverse_label',
            field=models.CharField(help_text='The reverse label of the edge class', max_length=1000, null=True),
        ),
    ]
