# Generated by Django 5.2 on 2026-02-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_edgequery_alter_nodequery_relevant_for_nodes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodePairsQuery",
            fields=[
                (
                    "nodequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.nodequery",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.nodequery",),
        ),
    ]
