# Generated by Django 4.2.8 on 2025-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_naturaleventcategory_plate_children"),
    ]

    operations = [
        migrations.RenameField(
            model_name="protocoleventcategory",
            old_name="target_definitions",
            new_name="target_entity_roles",
        ),
        migrations.RemoveField(
            model_name="protocoleventcategory",
            name="source_definitions",
        ),
        migrations.AddField(
            model_name="protocoleventcategory",
            name="source_entity_roles",
            field=models.JSONField(
                default=list,
                help_text="The categories or expressions that an event of this class can source from (source edges)",
            ),
        ),
        migrations.AddField(
            model_name="protocoleventcategory",
            name="source_reagent_roles",
            field=models.JSONField(
                default=list,
                help_text="The categories or expressions that an event of this class can source from (source edges)",
            ),
        ),
        migrations.AddField(
            model_name="protocoleventcategory",
            name="target_reagent_roles",
            field=models.JSONField(
                default=list,
                help_text="The categories or expressions that an of this class can target to (target edges)",
            ),
        ),
    ]
