# Generated by Django 5.2 on 2026-03-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_store_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materializededge',
            name='edge',
        ),
        migrations.RemoveField(
            model_name='materializededge',
            name='role',
        ),
        migrations.RemoveField(
            model_name='materializededge',
            name='source',
        ),
        migrations.RemoveField(
            model_name='materializededge',
            name='target',
        ),
        migrations.CreateModel(
            name='MaterializedRelationEdge',
            fields=[
                ('materializededge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.materializededge')),
                ('role', models.CharField(blank=True, help_text='The role of the edge, if its part of a protocol or natural event (e.g. source, target, etc.)', max_length=1000, null=True)),
                ('edge', models.ForeignKey(db_column='relation_id', help_text='The relation category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_relation_edges_as_relation', to='core.relationcategory')),
                ('source', models.ForeignKey(help_text='The source category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_relation_edges_as_source', to='core.entitycategory')),
                ('target', models.ForeignKey(help_text='The target category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_relation_edges_as_target', to='core.entitycategory')),
            ],
            bases=('core.materializededge',),
        ),
        migrations.CreateModel(
            name='MaterializedStructureRelationEdge',
            fields=[
                ('materializededge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.materializededge')),
                ('role', models.CharField(blank=True, help_text='The role of the edge, if its part of a protocol or natural event (e.g. source, target, etc.)', max_length=1000, null=True)),
                ('edge', models.ForeignKey(db_column='relation_id', help_text='The relation category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_structure_relation_edges_as_relation', to='core.structurerelationcategory')),
                ('source', models.ForeignKey(help_text='The source category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_structure_relation_edges_as_source', to='core.structurecategory')),
                ('target', models.ForeignKey(help_text='The target category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_structure_relation_edges_as_target', to='core.structurecategory')),
            ],
            bases=('core.materializededge',),
        ),
    ]
