# Generated by Django 5.2 on 2025-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_graphquery_node_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitycategory',
            name='variable_definitions',
        ),
        migrations.AddField(
            model_name='nodecategory',
            name='property_definitions',
            field=models.JSONField(default=list, help_text='The property definitions of this'),
        ),
    ]
