# Generated by Django 5.2 on 2025-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_edgecategory_reverse_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytag',
            options={'default_related_name': 'category_tags'},
        ),
        migrations.AlterField(
            model_name='categorytag',
            name='value',
            field=models.CharField(help_text='The value of the tag', max_length=1000),
        ),
        migrations.AlterField(
            model_name='edgecategory',
            name='source_definition',
            field=models.JSONField(default=dict, help_text='Filters for the right side of the edge (e.g. which tags the right side should have)', null=True),
        ),
        migrations.AlterField(
            model_name='edgecategory',
            name='target_definition',
            field=models.JSONField(default=dict, help_text='Filters for the left side of the edge (e.g. which tags the left side should have)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categorytag',
            unique_together={('graph', 'value')},
        ),
    ]
