# Generated by Django 6.0.3 on 2026-08-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_historicalgraph_assignation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='selector',
            field=models.JSONField(blank=True, default=dict, help_text="Declarative definition of which of the organization's evidence this graph projects. A graph is a view now, not a silo: membership is evaluated from this selector into a droppable cache, never maintained on write — otherwise every ingest would have to know about every projection. Shape: {category_keys: [...], assertion_filter: {subjects, app_ids, action_names}, as_of: timestamp, observed_window: [from, to]}. Consumed by the projector in M3; inert until then."),
        ),
        migrations.AddField(
            model_name='historicalgraph',
            name='selector',
            field=models.JSONField(blank=True, default=dict, help_text="Declarative definition of which of the organization's evidence this graph projects. A graph is a view now, not a silo: membership is evaluated from this selector into a droppable cache, never maintained on write — otherwise every ingest would have to know about every projection. Shape: {category_keys: [...], assertion_filter: {subjects, app_ids, action_names}, as_of: timestamp, observed_window: [from, to]}. Consumed by the projector in M3; inert until then."),
        ),
    ]
