# Generated by Django 4.2.8 on 2025-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0004_rename_target_definitions_protocoleventcategory_target_entity_roles_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="purl",
            field=models.CharField(
                blank=True,
                help_text="The name of the entity group",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgraph",
            name="purl",
            field=models.CharField(
                blank=True,
                help_text="The name of the entity group",
                max_length=1000,
                null=True,
            ),
        ),
    ]
