# Generated by Django 5.2 on 2026-02-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_nodepairsquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgePairsQuery",
            fields=[
                (
                    "edgequery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.edgequery",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.edgequery",),
        ),
    ]
