# Generated by Django 4.2.8 on 2025-02-22 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_measurementcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scatterplot",
            name="creator",
            field=models.ForeignKey(
                default=1,
                help_text="The user that created the scatter plot",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
