# Generated by Django 5.2 on 2026-03-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_remove_materializededge_edge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materializededge',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='materializedrelationedge',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='materializedstructurerelationedge',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='materializededge',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
