# Generated by Django 5.2 on 2026-02-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_edgepairsquery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metriccategory",
            old_name="metric_kind",
            new_name="value_kind",
        ),
    ]
