# Generated by Django 5.2 on 2025-09-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categorytag_options_alter_categorytag_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metriccategory',
            name='structure_definition',
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='structure_category',
            field=models.ForeignKey(default=1, help_text='The structure category that this metric describes', on_delete=django.db.models.deletion.CASCADE, related_name='metric_categories', to='core.structurecategory'),
            preserve_default=False,
        ),
    ]
