# Generated by Django 4.2.8 on 2025-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_scatterplot_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="scatterplot",
            name="x_id_column",
            field=models.CharField(
                help_text="The column that assigns the x_id value",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="y_id_column",
            field=models.CharField(
                help_text="The column that assigns an ID to the y value",
                max_length=1000,
                null=True,
            ),
        ),
    ]
