# Generated by Django 4.2.8 on 2025-03-31 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_graph_purl_historicalgraph_purl"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
