# Generated by Django 6.0.3 on 2026-08-11 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_graph_selector_historicalgraph_selector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graphschema',
            name='hash',
            field=models.CharField(db_index=True, default='', help_text="Content hash of `definition`. This is the identity a projected node stamps as its `__schema_version`, so a derived value can be told apart from one computed under an older schema. Distinct from `NodeCategory.schema_hash`, which hashes one category's properties rather than the whole graph definition.", max_length=64),
        ),
        migrations.AddConstraint(
            model_name='graphschema',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('graph',), name='one_active_schema_per_graph'),
        ),
    ]
