# Generated by Django 5.2 on 2026-02-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_metric_kind_metriccategory_value_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edgequery",
            options={
                "base_manager_name": "objects",
                "default_related_name": "edge_queries",
            },
        ),
        migrations.AlterModelOptions(
            name="graphquery",
            options={
                "base_manager_name": "objects",
                "default_related_name": "graph_queries",
            },
        ),
        migrations.AlterModelOptions(
            name="nodequery",
            options={
                "base_manager_name": "objects",
                "default_related_name": "node_queries",
            },
        ),
        migrations.AddField(
            model_name="edgequery",
            name="key",
            field=models.CharField(
                default=1,
                help_text="The key of the query, used for referencing the query in the frontend and for pinning it",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="graphquery",
            name="key",
            field=models.CharField(
                default=1,
                help_text="The key of the query, used for referencing the query in the frontend and for pinning it",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nodequery",
            name="key",
            field=models.CharField(
                default=1,
                help_text="The key of the query, used for referencing the query in the frontend and for pinning it",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="edgequery",
            unique_together={("graph", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="graphquery",
            unique_together={("graph", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="nodequery",
            unique_together={("graph", "key")},
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the protocol", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the protocol",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "plate_children",
                    models.JSONField(
                        default=list,
                        help_text="The steps of the protocol, each step is a dict with the following keys: name, description, event_category, source_entities, target_entities, source_reagents, target_reagents, variables",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="The graph this protocol belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="core.graph",
                    ),
                ),
            ],
        ),
    ]
