# Generated by Django 5.2 on 2025-09-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_metriccategory_structure_definition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ForeignKey(help_text='The graph this edge belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges', to='core.graph')),
                ('relation', models.ForeignKey(help_text='The relation category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_relation', to='core.category')),
                ('source', models.ForeignKey(help_text='The source category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_source', to='core.category')),
                ('target', models.ForeignKey(help_text='The target category of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='materialized_edges_as_target', to='core.category')),
            ],
        ),
    ]
