# Generated by Django 6.0.3 on 2026-08-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_graphschema_hash_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphschema',
            unique_together={('graph', 'index')},
        ),
    ]
