# Generated by Django 4.2.8 on 2025-04-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_category_pinned_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        help_text="The index name that was created", max_length=1000
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="The graph this sequence belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_sequences",
                        to="core.graph",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="index",
            field=models.ForeignKey(
                blank=True,
                help_text="The index of this category (new entities will be created with this index)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.graphsequence",
            ),
        ),
    ]
