# Generated by Django 4.2.8 on 2025-02-24 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_scatterplot_x_id_column_scatterplot_y_id_column"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time the view was created"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The user that created the view",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="The graph this view belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_views",
                        to="core.graph",
                    ),
                ),
                (
                    "pinned_by",
                    models.ManyToManyField(
                        help_text="The users that pinned the view",
                        related_name="pinned_plotviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        help_text="The scatter plot this view belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.scatterplot",
                    ),
                ),
            ],
        ),
    ]
