# Generated by Django 5.2 on 2026-02-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_edgequery_options_alter_graphquery_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scatterplot",
            name="query",
        ),
        migrations.RemoveField(
            model_name="scatterplot",
            name="view",
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="graph_query",
            field=models.ForeignKey(
                blank=True,
                help_text="The query this scatter plot was trained on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to="core.graphtablequery",
            ),
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="node_query",
            field=models.ForeignKey(
                blank=True,
                help_text="The node query this scatter plot was trained on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to="core.nodetablequery",
            ),
        ),
        migrations.AddField(
            model_name="scatterplot",
            name="path_query",
            field=models.ForeignKey(
                blank=True,
                help_text="The path query this scatter plot was trained on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scatter_plots",
                to="core.nodepathquery",
            ),
        ),
    ]
