# Generated by Django 4.2.8 on 2025-02-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_plotview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotview",
            name="graph",
        ),
        migrations.AddField(
            model_name="plotview",
            name="view",
            field=models.ForeignKey(
                default=1,
                help_text="The graph this view belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_views",
                to="core.graphview",
            ),
            preserve_default=False,
        ),
    ]
