# Generated by Django 5.2 on 2026-02-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_graphschema_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodecategory",
            name="schema_hash",
            field=models.CharField(
                default="",
                help_text="The schema hash representing the version of the schema this category was defined with",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="edge_deletion_allowed",
            field=models.BooleanField(
                default=True, help_text="If edge deletion is allowed in this graph"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraph",
            name="edge_deletion_allowed",
            field=models.BooleanField(
                default=True, help_text="If edge deletion is allowed in this graph"
            ),
        ),
        migrations.CreateModel(
            name="GraphOntology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the ontology", max_length=1000
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="The URL of the ontology", max_length=2000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of the ontology",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="The graph this ontology belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ontologies",
                        to="core.graph",
                    ),
                ),
            ],
            options={
                "default_related_name": "graph_ontologies",
                "unique_together": {("graph", "name")},
            },
        ),
        migrations.CreateModel(
            name="OntologyReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the ontology reference", max_length=1000
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ontology_references",
                        to="core.category",
                    ),
                ),
                (
                    "ontology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="core.graphontology",
                    ),
                ),
            ],
        ),
    ]
