# Generated by Django 4.2.8 on 2025-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_graphsequence_category_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graphsequence",
            options={"default_related_name": "graph_sequences"},
        ),
        migrations.AddField(
            model_name="graphsequence",
            name="cycle",
            field=models.BooleanField(
                default=False,
                help_text="If the sequence is circular (e.g. 1,2,3,4,5,1,2,3,4,5)",
            ),
        ),
        migrations.AddField(
            model_name="graphsequence",
            name="max_value",
            field=models.IntegerField(
                blank=True,
                help_text="The maximum value of the sequence (can be null if not set)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="graphsequence",
            name="min_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="graphsequence",
            name="start_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="graphsequence",
            name="step_size",
            field=models.IntegerField(
                default=1, help_text="The step size of the sequence (e.g. 1,2,3,4,5,6)"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="graphsequence",
            unique_together={("graph", "index")},
        ),
    ]
