# Generated by Django 4.2.8 on 2025-04-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_graphsequence_options_graphsequence_cycle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="index",
            field=models.ForeignKey(
                blank=True,
                help_text="The index of this category (new entities will be created with this index)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.graphsequence",
            ),
        ),
    ]
