# Generated by Django 6.0.3 on 2026-08-16 10:38

"""Three models nothing ever wrote, and one input the API accepted and dropped.

- **`GraphSequence`** plus `Category.sequence`. No `GraphSequence.objects.*`
  exists anywhere and the foreign key was never set. Worse, the API *advertised*
  it: `GraphDefinitionInput.sequences` and `DefinitionInput.sequences` accepted
  sequence declarations, `SequenceMappingInput.property` documented "the property
  key that will be set with the sequence value" — and `materialize.py` never read
  `definition.sequences` at all. Those inputs go with the table.
- **`Protocol`** (the `core` one, unrelated to `ProtocolEventCategory` and to
  `typing.Protocol`). No manager use, no foreign key pointing at it, no GraphQL
  type.
- **`Descriptor`**. Same: no manager use, no GraphQL type, and nothing consumed
  its `descriptors` related name.

`GraphOntology` and `OntologyReference` look similar and are **not** dead — four
schema resolvers read and write them. They stay.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_materialized_edges_die'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphsequence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='graphsequence',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='graph',
        ),
        migrations.DeleteModel(
            name='Descriptor',
        ),
        migrations.DeleteModel(
            name='GraphSequence',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
