# Generated by Django 4.2.8 on 2025-02-25 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_remove_plotview_graph_plotview_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphquery",
            name="active_for",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="active_graph_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nodequery",
            name="active_for",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="active_node_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
