# Generated by Django 4.2.8 on 2025-02-25 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_graphquery_active_for_nodequery_active_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="active_for",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="active_graphs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
