# Generated by Django 4.2.8 on 2025-02-25 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_graph_active_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graph",
            name="active_for",
        ),
        migrations.RemoveField(
            model_name="graphquery",
            name="active_for",
        ),
        migrations.RemoveField(
            model_name="nodequery",
            name="active_for",
        ),
        migrations.AddField(
            model_name="graph",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_graphs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graphquery",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_graph_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nodequery",
            name="pinned_by",
            field=models.ManyToManyField(
                help_text="The users that have this query active",
                related_name="pinned_node_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
