# Generated by Django 6.0.3 on 2026-09-02 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_saved_queries_are_plans'),
        ('datalayer', '0001_initial'),
        ('evidence', '0010_comment_is_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('graph', 'id'), name='category_graph_and_id'),
        ),
    ]
