# Generated by Django 4.2.8 on 2025-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_graphquery_relevant_for_nodequery_relevant_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="position_x",
            field=models.FloatField(
                help_text="The x position of the entity class in the graph", null=True
            ),
        ),
        migrations.AddField(
            model_name="expression",
            name="position_y",
            field=models.FloatField(
                help_text="The y position of the entity class in the graph", null=True
            ),
        ),
    ]
