# Generated by Django 6.0.3 on 2026-09-02 09:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_category_graph_and_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='age_name',
            field=models.CharField(default=core.models.new_projection_handle, editable=False, help_text="Internal handle naming this graph's namespace: the per-graph Postgres schema holding its views and SQL/PGQ property graph, derived from the categories by `refresh_namespace` (RFC 0006). Random, assigned at creation, a name for *output* only — never accepted as input: a graph is addressed by its primary key. See `new_projection_handle`.", max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalgraph',
            name='age_name',
            field=models.CharField(db_index=True, default=core.models.new_projection_handle, editable=False, help_text="Internal handle naming this graph's namespace: the per-graph Postgres schema holding its views and SQL/PGQ property graph, derived from the categories by `refresh_namespace` (RFC 0006). Random, assigned at creation, a name for *output* only — never accepted as input: a graph is addressed by its primary key. See `new_projection_handle`.", max_length=63),
        ),
    ]
