# Generated by Django 4.2.8 on 2025-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_expression_position_x_expression_position_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="height",
            field=models.FloatField(
                help_text="The height of the entity class in the graph", null=True
            ),
        ),
        migrations.AddField(
            model_name="expression",
            name="width",
            field=models.FloatField(
                help_text="The width of the entity class in the graph", null=True
            ),
        ),
    ]
