# Generated by Django 4.2.8 on 2025-03-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_expression_height_expression_width"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepCategory",
            fields=[
                (
                    "expression_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.expression",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template that was used to create the step",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_categories",
                        to="core.protocolsteptemplate",
                    ),
                ),
            ],
            options={
                "default_related_name": "step_categories",
            },
            bases=("core.expression",),
        ),
    ]
