# Generated by Django 6.0.3 on 2026-09-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_category_definition_alter_graph_selector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='selector',
        ),
        migrations.RemoveField(
            model_name='historicalgraph',
            name='selector',
        ),
    ]
