# Generated by Django 6.0.3 on 2026-09-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_definitions_are_rule_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='historicalgraph',
            name='rules',
        ),
    ]
