# Generated by Django 6.0.3 on 2026-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatalayerStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BIG_FILE', 'Big File'), ('MEDIA', 'Media'), ('ZARR', 'Zarr'), ('PARQUET', 'Parquet')], help_text='Which kind of object this store points at.', max_length=32)),
                ('path', models.CharField(blank=True, help_text='The object-store URI of the file', max_length=1000, null=True, unique=True)),
                ('key', models.CharField(help_text='The object key/path within the datalayer bucket.', max_length=1000)),
                ('bucket', models.CharField(help_text='The datalayer bucket/service this store belongs to.', max_length=1000)),
                ('original_file_name', models.CharField(blank=True, help_text='The original client-provided file name.', max_length=1000, null=True)),
                ('content_type', models.CharField(blank=True, help_text='The client-provided content type for the uploaded file.', max_length=255, null=True)),
                ('populated', models.BooleanField(default=False, help_text='Whether the store has been populated with a valid path and is ready for use.')),
                ('shape', models.JSONField(blank=True, help_text='The shape of the Zarr array stored at this location.', null=True)),
                ('chunks', models.JSONField(blank=True, help_text='The chunk size of the Zarr array stored at this location.', null=True)),
                ('version', models.CharField(blank=True, help_text='The Zarr format version of the array stored at this location.', max_length=10, null=True)),
                ('dtype', models.CharField(blank=True, help_text='The dtype of the Zarr array stored at this location.', max_length=255, null=True)),
                ('dimension_names', models.JSONField(blank=True, help_text='The dimension names declared by the Zarr array.', null=True)),
                ('fill_value', models.JSONField(blank=True, help_text='The fill value declared by the Zarr array.', null=True)),
                ('attributes', models.JSONField(blank=True, help_text='The user attributes stored in zarr.json.', null=True)),
                ('storage_transformers', models.JSONField(blank=True, help_text='The storage transformers declared by the Zarr array.', null=True)),
                ('chunk_key_encoding', models.JSONField(blank=True, help_text='The chunk key encoding configuration for the Zarr array.', null=True)),
                ('codecs', models.JSONField(blank=True, help_text='The codec pipeline declared for the Zarr array.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BigFileStore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='MediaStore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='ParquetStore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='ZarrStore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datalayer.datalayerstore',),
        ),
    ]
