# Generated by Django 5.2 on 2026-02-16 14:46

import datalayer.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="S3Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    datalayer.fields.S3Field(
                        blank=True,
                        help_text="The stodre of the image",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                ("key", models.CharField(max_length=1000)),
                ("bucket", models.CharField(max_length=1000)),
                ("populated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BigFileStore",
            fields=[
                (
                    "s3store_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="datalayer.s3store",
                    ),
                ),
            ],
            bases=("datalayer.s3store",),
        ),
        migrations.CreateModel(
            name="MediaStore",
            fields=[
                (
                    "s3store_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="datalayer.s3store",
                    ),
                ),
            ],
            bases=("datalayer.s3store",),
        ),
    ]
