"""
Django settings for the kraph service.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from .configuration import Settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
conf = Settings()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# The key comes from config and has no default: boot fails when it is unset.
SECRET_KEY = conf.django.secret_key

# Every one of these used to be a literal (`DEBUG = True`, `ALLOWED_HOSTS = ["*"]`)
# while `configuration.py` parsed `django.debug` / `django.hosts` /
# `django.use_x_forwarded_host` and nothing read them — production served full
# tracebacks and kept every SQL query in memory. `manage.py check --deploy`
# (run.sh) is what tells you when a deployment turns debug on.
DEBUG = conf.django.debug
ALLOWED_HOSTS: list[str] = list(conf.django.hosts)
USE_X_FORWARDED_HOST = conf.django.use_x_forwarded_host
# Behind the deployment proxy the request reaches daphne over plain http. Trust the
# proxy's protocol header exactly when we already trust its host header; a proxy
# that forwards `X-Forwarded-Proto` must overwrite a client-sent one.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if conf.django.use_x_forwarded_host else None

# TLS termination and HSTS belong to the proxy in front of daphne; local
# deployments serve plain http on purpose. Secure-cookie warnings (W012/W016) stay
# visible: they are a real trade-off, not noise.
SILENCED_SYSTEM_CHECKS = ["security.W004", "security.W008"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "channels_redis",
    "datalayer",
    "simple_history",
    "strawberry",
    "strawberry_django",
    "authentikate",
    "koherent",
    "kante",
    "channels",
    "django_probes",
    "core",
    "graph_engine",
    "evidence",
    "health_check",  # required for health checks
    "health_check.db",  # stock Django health checkers
    "health_check.contrib.redis",  # the channel layer; a dead redis is a dead subscription
]


AUTH_USER_MODEL = "authentikate.User"

AWS_ACCESS_KEY_ID = conf.datalayer.access_key
AWS_SECRET_ACCESS_KEY = conf.datalayer.secret_key
AWS_S3_ENDPOINT_URL = f"{conf.datalayer.protocol}://{conf.datalayer.host}:{conf.datalayer.port}"
AWS_S3_URL_PROTOCOL = f"{conf.datalayer.protocol}:"
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_EXPIRE = 3600
AWS_S3_REGION_NAME = conf.datalayer.region

FILE_BUCKET = conf.datalayer.media.bucket
MEDIA_BUCKET = conf.datalayer.media.bucket

AWS_STORAGE_BUCKET_NAME = conf.datalayer.media.bucket
AWS_DEFAULT_ACL = "private"
AWS_S3_USE_SSL = True
AWS_S3_SECURE_URLS = False


DATALAYER = conf.datalayer.model_dump(exclude_none=True) if conf.datalayer else {}


CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(conf.redis.host, conf.redis.port)], "prefix": "kraph"},
    },
}

# `health_check.contrib.redis` pings this. Fail fast: the probe must not hang on a dead redis.
REDIS_URL = f"redis://{conf.redis.host}:{conf.redis.port}/0"
HEALTHCHECK_REDIS_URL_OPTIONS = {"socket_connect_timeout": 2}

# `graph_engine.health.ProjectionLagHealthCheck` warns when a consistent view is
# further than this many acts behind its organization's log.
PROJECTION_LAG_THRESHOLD = conf.projection.lag_threshold


CSRF_TRUSTED_ORIGINS = conf.django.csrf_trusted_origins
MY_SCRIPT_NAME = conf.django.force_script_name

STRAWBERRY_DJANGO = {
    "USE_DEPRECATED_FILTERS": True,
    "DEFAULT_PK_FIELD_NAME": "id",
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kraph_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

WSGI_APPLICATION = "kraph_server.wsgi.application"
ASGI_APPLICATION = "kraph_server.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": conf.postgres.engine,
        "NAME": conf.postgres.db_name,
        "USER": conf.postgres.username,
        "PASSWORD": conf.postgres.password,
        "HOST": conf.postgres.host,
        "PORT": conf.postgres.port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


AUTHENTIKATE = conf.authentikate.model_dump()

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# WhiteNoise serves static directly from the staticfiles finders at request time
# (works under both runserver and daphne), so no collectstatic / STATIC_ROOT is needed.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
