# Generated by Django 6.0.3 on 2026-08-13 19:45

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('datalayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Who made the claim — a user id, or the identity of an automated agent.', max_length=1000)),
                ('app_id', models.CharField(help_text='Which application made the claim.', max_length=1000)),
                ('action_id', models.CharField(blank=True, db_index=True, help_text='Identity of the action that produced this assertion, where there was one. `ProvenanceContext` has always carried this; the first version of this model dropped it, which left provenance unable to name what actually ran.', max_length=1000, null=True)),
                ('action_name', models.CharField(blank=True, help_text='Human-readable name of the action that produced this assertion.', max_length=1000, null=True)),
                ('action_args', models.JSONField(blank=True, default=dict, help_text='Arguments the action ran with, kept so the claim can be reproduced.')),
                ('asserted_at', models.DateTimeField(db_index=True, help_text='When the claim was made. Belief time — this is the axis `as_of` filters on.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When we durably stored the claim. Never equal to asserted_at by definition, and only ever used for debugging ingest, not for answering questions.')),
                ('organization', models.ForeignKey(help_text='The tenant this assertion belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(help_text="Which table the target lives in: 'structure', 'metric', 'link' or 'node'.", max_length=32)),
                ('target_id', models.CharField(help_text='Opaque uuid of the target row. A CharField rather than a UUIDField because the column addresses four different tables; see the note on Link about keeping refs opaque.', max_length=1000)),
                ('stands', models.BooleanField(help_text='Whether the claimant says this stands. True attests, False retracts. Deliberately not nullable: a claim with no position is not a claim.')),
                ('at', models.DateTimeField(help_text='When the claim took effect. World time, the axis a scientist means.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text="When we durably stored the claim. Exists to break ties between claims sharing an `at` — two written in one request both default to `now()`, and without a second key `.first()` would return either. A tiebreak, not a total order: see the 'No total order' gap in docs/LOG.md, which this does not close.")),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MetricKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="The measurement key, e.g. 'vector_length'.", max_length=1000)),
                ('value_kind', models.CharField(choices=[('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATETIME', 'DATETIME'), ('STRING', 'STRING'), ('CATEGORY', 'CATEGORY'), ('BOOLEAN', 'BOOLEAN'), ('THREE_D_VECTOR', 'THREE_D_VECTOR'), ('TWO_D_VECTOR', 'TWO_D_VECTOR'), ('ONE_D_VECTOR', 'ONE_D_VECTOR'), ('FOUR_D_VECTOR', 'FOUR_D_VECTOR'), ('N_VECTOR', 'N_VECTOR')], help_text='What type of value this measurement carries. Non-null: a term whose type is unknown cannot say which column its values belong in.', max_length=32)),
                ('label', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('purl', models.CharField(blank=True, max_length=1000, null=True)),
                ('color', models.JSONField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_kinds', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text="The structure identifier, e.g. '@mikro/roi'. Denormalized from `kind` because uniqueness has to be expressible as a table constraint, and **this column is the one that counts**: the unique constraint and every structure filter read it, not the foreign key. `ensure_structure` sets the two consistently and nothing else should write either.", max_length=1000)),
                ('object', models.CharField(help_text='The id of the external object this structure points at.', max_length=1000)),
                ('stands', models.BooleanField(default=True, help_text='Cache of the latest Claim about this row. Derived, never authoritative — the claims are.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(help_text='The assertion that first introduced this structure.', on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="The measurement key, e.g. 'vector_length'.", max_length=1000)),
                ('value_kind', models.CharField(choices=[('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATETIME', 'DATETIME'), ('STRING', 'STRING'), ('CATEGORY', 'CATEGORY'), ('BOOLEAN', 'BOOLEAN'), ('THREE_D_VECTOR', 'THREE_D_VECTOR'), ('TWO_D_VECTOR', 'TWO_D_VECTOR'), ('ONE_D_VECTOR', 'ONE_D_VECTOR'), ('FOUR_D_VECTOR', 'FOUR_D_VECTOR'), ('N_VECTOR', 'N_VECTOR')], help_text="Which of the value_* columns carries this metric's value.", max_length=32)),
                ('value_num', models.FloatField(blank=True, help_text='INT and FLOAT values. Numeric so aggregation stays in the database.', null=True)),
                ('value_txt', models.TextField(blank=True, help_text='STRING and CATEGORY values.', null=True)),
                ('value_bool', models.BooleanField(blank=True, help_text='BOOLEAN values.', null=True)),
                ('value_time', models.DateTimeField(blank=True, help_text='DATETIME values. Given a real column rather than an epoch int so it stays orderable and indexable.', null=True)),
                ('value_json', models.JSONField(blank=True, help_text='Vector values (ONE_D through N_VECTOR), stored as a list of floats.', null=True)),
                ('unit', models.CharField(blank=True, max_length=1000, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('confidence_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('measured_at', models.DateTimeField(db_index=True, help_text="When the world was observed. The axis a scientist means by 'when'.")),
                ('asserted_at', models.DateTimeField(db_index=True, help_text='When this measurement was claimed. Denormalized from the assertion so `as_of` filtering does not need a join on the hottest table.')),
                ('stands', models.BooleanField(default=True, help_text='Cache of the latest Claim about this row. Derived, never authoritative.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='authentikate.organization')),
                ('kind', models.ForeignKey(help_text="The organization's term for this kind of measurement.", on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='evidence.metrickind')),
                ('structure', models.ForeignKey(help_text='The structure this metric describes.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='evidence.structure')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StructureKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text="The structure identifier, e.g. '@mikro/roi'. Owned by the service that produces the datum.", max_length=1000)),
                ('label', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('purl', models.CharField(blank=True, help_text='Persistent URL, where this kind corresponds to a published ontology term.', max_length=1000, null=True)),
                ('color', models.JSONField(blank=True, help_text='Display colour as RGBA.', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalayer.mediastore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_kinds', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='structure',
            name='kind',
            field=models.ForeignKey(help_text="The organization's term for this kind of structure.", on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='evidence.structurekind'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_ref', models.CharField(help_text='Opaque uuid of the node or edge this statistic describes. Do not parse.', max_length=1000)),
                ('key', models.CharField(help_text='The measurement key being folded.', max_length=1000)),
                ('value_kind', models.CharField(choices=[('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATETIME', 'DATETIME'), ('STRING', 'STRING'), ('CATEGORY', 'CATEGORY'), ('BOOLEAN', 'BOOLEAN'), ('THREE_D_VECTOR', 'THREE_D_VECTOR'), ('TWO_D_VECTOR', 'TWO_D_VECTOR'), ('ONE_D_VECTOR', 'ONE_D_VECTOR'), ('FOUR_D_VECTOR', 'FOUR_D_VECTOR'), ('N_VECTOR', 'N_VECTOR')], help_text="The value kind of the metrics folded here. Part of the grain: a key with a FLOAT term and a STRING term maintains two rows, so neither aggregation is polluted by the other's values.", max_length=32)),
                ('n', models.PositiveIntegerField(default=0, help_text='Count of contributing metrics. COUNT reads this.')),
                ('sum', models.FloatField(blank=True, help_text='Running sum of numeric values. MEAN is sum/n; SUM reads it directly.', null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('first_ts', models.DateTimeField(blank=True, help_text='measured_at of the earliest contributing metric.', null=True)),
                ('last_ts', models.DateTimeField(blank=True, help_text='measured_at of the latest contributing metric.', null=True)),
                ('first_value', models.JSONField(blank=True, help_text='Value at first_ts. JSON rather than typed because LATEST is defined over strings and vectors too, and EUCLIDEAN_RANGE reads this as a point — which is why there is no separate first_pt column duplicating it.', null=True)),
                ('last_value', models.JSONField(blank=True, help_text='Value at last_ts. LATEST reads this.', null=True)),
                ('needs_recompute', models.BooleanField(default=False, help_text='Set when a retraction invalidated an order-dependent statistic (MIN/MAX/LATEST and friends cannot be un-merged). Read as: this row is stale until `recompute` runs.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('high_water_assertion', models.ForeignKey(blank=True, help_text='The latest assertion folded in. Lets a retraction arriving mid-backfill be ordered against what has already been counted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_water_states', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='authentikate.organization')),
                ('source_kind', models.ForeignKey(help_text='The kind of structure the measurements came through.', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='evidence.structurekind')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='metrickind',
            name='structure_kind',
            field=models.ForeignKey(help_text='The kind of structure this measurement describes.', on_delete=django.db.models.deletion.CASCADE, related_name='metric_kinds', to='evidence.structurekind'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(help_text='What sort of thing this term names — ENTITY, RELATION, NATURAL_EVENT, and so on. Mirrors `core.enums.CategoryKindChoices`.', max_length=32)),
                ('key', models.CharField(help_text="The word itself, e.g. 'AIS'. What a classification claim means when it names this term.", max_length=1000)),
                ('label', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('purl', models.CharField(blank=True, help_text='Persistent URL, where this term corresponds to a published ontology term.', max_length=1000, null=True)),
                ('color', models.JSONField(blank=True, help_text='Display colour as RGBA.', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalayer.mediastore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('entity', 'Entity'), ('natural_event', 'Natural event'), ('protocol_event', 'Protocol event')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(help_text='The assertion that first claimed this node exists.', on_delete=django.db.models.deletion.PROTECT, related_name='projected_nodes', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_nodes', to='authentikate.organization')),
                ('term', models.ForeignKey(help_text="The organization's word this node was first claimed under. Which view shows it, and as what, is decided from the claims — see `projector.resolve_categories`.", on_delete=django.db.models.deletion.PROTECT, related_name='projected_nodes', to='evidence.term')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('informs', 'Informs'), ('relation', 'Relation'), ('structure_relation', 'Structure relation'), ('measurement', 'Measurement'), ('participates_as_input', 'Participates as input'), ('participates_as_output', 'Participates as output'), ('classifies', 'Classifies')], max_length=32)),
                ('source_ref', models.CharField(help_text='Opaque uuid of the source row. Do not parse.', max_length=1000)),
                ('target_ref', models.CharField(help_text='Opaque uuid of the target row. Do not parse.', max_length=1000)),
                ('role', models.CharField(blank=True, help_text="Which role the source plays, for participation links. The schema names it; it is projected as a property on the edge rather than folded into the edge label, so that 'everything that went into this event' stays answerable without enumerating roles.", max_length=1000, null=True)),
                ('stands', models.BooleanField(default=True, help_text='Cache of the latest Claim about this row. Derived, never authoritative.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='authentikate.organization')),
                ('term', models.ForeignKey(blank=True, help_text="The organization's word for this link, where one applies. Plain INFORMS links carry no term.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='evidence.term')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='assertion',
            index=models.Index(fields=['organization', 'asserted_at'], name='evidence_as_organiz_077b12_idx'),
        ),
        migrations.AddIndex(
            model_name='assertion',
            index=models.Index(fields=['organization', 'subject'], name='evidence_as_organiz_3cc0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['organization', 'target_type', 'target_id', '-at', '-recorded_at'], name='evidence_cl_organiz_dfee00_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['organization', 'structure', 'key'], name='evidence_me_organiz_ae1de4_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['organization', 'kind'], name='evidence_me_organiz_f70894_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['organization', 'asserted_at'], name='evidence_me_organiz_404263_idx'),
        ),
        migrations.AddConstraint(
            model_name='structurekind',
            constraint=models.UniqueConstraint(fields=('organization', 'identifier'), name='unique_structure_kind_per_organization'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['organization', 'kind'], name='evidence_st_organiz_34c124_idx'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.UniqueConstraint(fields=('organization', 'identifier', 'object'), name='unique_structure_per_organization'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['organization', 'entity_ref'], name='evidence_st_organiz_db1935_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['organization', 'needs_recompute'], name='evidence_st_organiz_b84f3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('organization', 'entity_ref', 'source_kind', 'key', 'value_kind'), name='unique_state_per_entity_source_kind_key_value_kind'),
        ),
        migrations.AddIndex(
            model_name='metrickind',
            index=models.Index(fields=['organization', 'structure_kind', 'key'], name='evidence_me_organiz_ed572d_idx'),
        ),
        migrations.AddConstraint(
            model_name='metrickind',
            constraint=models.UniqueConstraint(fields=('organization', 'structure_kind', 'key', 'value_kind'), name='unique_metric_kind_per_value_kind'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('organization', 'kind', 'key'), name='unique_term_per_organization'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['organization', 'kind'], name='evidence_no_organiz_072485_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['organization', 'term'], name='evidence_no_organiz_54ce2f_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['organization', 'kind', 'source_ref'], name='evidence_li_organiz_effd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['organization', 'kind', 'target_ref'], name='evidence_li_organiz_d0da01_idx'),
        ),
    ]
