# Generated by Django 6.0.3 on 2026-08-11 17:42

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0004_remove_historicalgraph_assignation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Who made the claim — a user id, or the identity of an automated agent.', max_length=1000)),
                ('app_id', models.CharField(help_text='Which application made the claim.', max_length=1000)),
                ('action_name', models.CharField(blank=True, help_text='Human-readable name of the action that produced this assertion.', max_length=1000, null=True)),
                ('action_args', models.JSONField(blank=True, default=dict, help_text='Arguments the action ran with, kept so the claim can be reproduced.')),
                ('asserted_at', models.DateTimeField(db_index=True, help_text='When the claim was made. Belief time — this is the axis `as_of` filters on.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When we durably stored the claim. Never equal to asserted_at by definition, and only ever used for debugging ingest, not for answering questions.')),
                ('organization', models.ForeignKey(help_text='The tenant this assertion belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(help_text="What kind of thing the target is: 'structure', 'metric', 'link' or 'entity'.", max_length=32)),
                ('target_id', models.CharField(help_text="Opaque reference to the target — an evidence row's uuid, or a projection-scoped entity ref. A CharField rather than a UUIDField precisely because entities are not evidence rows yet; see the note on Link about keeping refs opaque.", max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], max_length=32)),
                ('at', models.DateTimeField(help_text='When the status change took effect.')),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('informs', 'Informs'), ('relation', 'Relation'), ('structure_relation', 'Structure relation'), ('measurement', 'Measurement')], max_length=32)),
                ('source_ref', models.CharField(help_text='Opaque reference to the source. Do not parse outside the projector.', max_length=1000)),
                ('target_ref', models.CharField(help_text='Opaque reference to the target. Do not parse outside the projector.', max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='evidence.assertion')),
                ('category', models.ForeignKey(blank=True, help_text='The ontology term for this link, where one applies. Plain INFORMS links carry no category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='core.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text="The structure identifier, e.g. '@mikro/roi'. Denormalized from the category because uniqueness has to be expressible as a table constraint.", max_length=1000)),
                ('object', models.CharField(help_text='The id of the external object this structure points at.', max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Cache of the latest LifecycleEvent for this row. Derived, not authoritative — the lifecycle log is.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(help_text='The assertion that first introduced this structure.', on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='evidence.assertion')),
                ('category', models.ForeignKey(help_text='The ontology term for this kind of structure.', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_structures', to='core.structurecategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="The measurement key, e.g. 'vector_length'.", max_length=1000)),
                ('value_kind', models.CharField(choices=[('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATETIME', 'DATETIME'), ('STRING', 'STRING'), ('CATEGORY', 'CATEGORY'), ('BOOLEAN', 'BOOLEAN'), ('THREE_D_VECTOR', 'THREE_D_VECTOR'), ('TWO_D_VECTOR', 'TWO_D_VECTOR'), ('ONE_D_VECTOR', 'ONE_D_VECTOR'), ('FOUR_D_VECTOR', 'FOUR_D_VECTOR'), ('N_VECTOR', 'N_VECTOR')], help_text="Which of the value_* columns carries this metric's value.", max_length=32)),
                ('value_num', models.FloatField(blank=True, help_text='INT and FLOAT values. Numeric so aggregation stays in the database.', null=True)),
                ('value_txt', models.TextField(blank=True, help_text='STRING and CATEGORY values.', null=True)),
                ('value_bool', models.BooleanField(blank=True, help_text='BOOLEAN values.', null=True)),
                ('value_time', models.DateTimeField(blank=True, help_text='DATETIME values. Given a real column rather than an epoch int so it stays orderable and indexable.', null=True)),
                ('value_json', models.JSONField(blank=True, help_text='Vector values (ONE_D through N_VECTOR), stored as a list of floats.', null=True)),
                ('unit', models.CharField(blank=True, max_length=1000, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('confidence_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('measured_at', models.DateTimeField(db_index=True, help_text="When the world was observed. The axis a scientist means by 'when'.")),
                ('asserted_at', models.DateTimeField(db_index=True, help_text='When this measurement was claimed. Denormalized from the assertion so `as_of` filtering does not need a join on the hottest table.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Cache of the latest LifecycleEvent for this row.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='evidence.assertion')),
                ('category', models.ForeignKey(help_text='The ontology term for this kind of measurement.', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_metrics', to='core.metriccategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='authentikate.organization')),
                ('structure', models.ForeignKey(help_text='The structure this metric describes.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='evidence.structure')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='assertion',
            index=models.Index(fields=['organization', 'asserted_at'], name='evidence_as_organiz_077b12_idx'),
        ),
        migrations.AddIndex(
            model_name='assertion',
            index=models.Index(fields=['organization', 'subject'], name='evidence_as_organiz_3cc0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecycleevent',
            index=models.Index(fields=['organization', 'target_type', 'target_id'], name='evidence_li_organiz_2a7986_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['organization', 'kind', 'source_ref'], name='evidence_li_organiz_effd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['organization', 'kind', 'target_ref'], name='evidence_li_organiz_d0da01_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['organization', 'category'], name='evidence_st_organiz_7e1812_idx'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.UniqueConstraint(fields=('organization', 'identifier', 'object'), name='unique_structure_per_organization'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['organization', 'structure', 'key'], name='evidence_me_organiz_ae1de4_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['organization', 'category'], name='evidence_me_organiz_c97548_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['organization', 'asserted_at'], name='evidence_me_organiz_404263_idx'),
        ),
    ]
