# Generated by Django 6.0.3 on 2026-08-11 18:40

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0005_graph_selector_historicalgraph_selector'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_ref', models.CharField(help_text='Opaque reference to the entity this statistic describes. Do not parse.', max_length=1000)),
                ('key', models.CharField(help_text='The measurement key being folded.', max_length=1000)),
                ('n', models.PositiveIntegerField(default=0, help_text='Count of contributing metrics. COUNT reads this.')),
                ('sum', models.FloatField(blank=True, help_text='Running sum of numeric values. MEAN is sum/n; SUM reads it directly.', null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('first_ts', models.DateTimeField(blank=True, help_text='measured_at of the earliest contributing metric.', null=True)),
                ('last_ts', models.DateTimeField(blank=True, help_text='measured_at of the latest contributing metric.', null=True)),
                ('first_value', models.JSONField(blank=True, help_text='Value at first_ts. JSON rather than typed because LATEST is defined over strings and vectors too, and EUCLIDEAN_RANGE reads this as a point — which is why there is no separate first_pt column duplicating it.', null=True)),
                ('last_value', models.JSONField(blank=True, help_text='Value at last_ts. LATEST reads this.', null=True)),
                ('needs_recompute', models.BooleanField(default=False, help_text='Set when a retraction invalidated an order-dependent statistic (MIN/MAX/LATEST and friends cannot be un-merged). Read as: this row is stale until `recompute` runs.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('high_water_assertion', models.ForeignKey(blank=True, help_text='The latest assertion folded in. Lets a retraction arriving mid-backfill be ordered against what has already been counted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_water_states', to='evidence.assertion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='authentikate.organization')),
                ('source_category', models.ForeignKey(help_text='The kind of structure the measurements came through.', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.structurecategory')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['organization', 'entity_ref'], name='evidence_st_organiz_db1935_idx'), models.Index(fields=['organization', 'needs_recompute'], name='evidence_st_organiz_b84f3e_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'entity_ref', 'source_category', 'key'), name='unique_state_per_entity_source_key')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
