# Generated by Django 6.0.3 on 2026-08-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('evidence', '0002_assertion_seq'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='claim',
            name='evidence_cl_organiz_dfee00_idx',
        ),
        migrations.AlterField(
            model_name='claim',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When we durably stored the claim. Debugging only. It used to break ties between claims sharing an `at`, and conceded in its own help_text that it was a tiebreak rather than a total order — two claims written in one request share it to the microsecond often enough that the fold could pick either. `Assertion.seq` is the tiebreak now.'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['organization', 'target_type', 'target_id', '-at', '-assertion'], name='evidence_cl_organiz_9ef309_idx'),
        ),
    ]
