# Generated by Django 6.0.3 on 2026-08-11 18:51

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0005_graph_selector_historicalgraph_selector'),
        ('evidence', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(help_text="Opaque durable identity, '{age_name}:{uuid}'. Do not parse outside the projector.", max_length=1000)),
                ('kind', models.CharField(choices=[('entity', 'Entity'), ('natural_event', 'Natural event'), ('protocol_event', 'Protocol event')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(help_text='The assertion that claimed this node exists.', on_delete=django.db.models.deletion.PROTECT, related_name='projected_nodes', to='evidence.assertion')),
                ('category', models.ForeignKey(help_text='The ontology term this node instantiates.', on_delete=django.db.models.deletion.CASCADE, related_name='projected_nodes', to='core.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_nodes', to='authentikate.organization')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['organization', 'kind'], name='evidence_no_organiz_072485_idx'), models.Index(fields=['organization', 'category'], name='evidence_no_organiz_2d70c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'ref'), name='unique_node_ref_per_organization')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
