# Generated by Django 6.0.3 on 2026-08-17 20:25

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentikate", "0006_alter_app_identifier_alter_release_unique_together"),
        ("evidence", "0008_instance_and_standing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standing",
            name="target_type",
            field=models.CharField(help_text="Which table the claim this is about lives in: 'structure', 'metric', 'link', 'comment' or 'node'.", max_length=32),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("descendants", models.JSONField(default=list, help_text="The rich representation of the remark — a tree of LEAF/MENTION/PARAGRAPH nodes, shape-compatible with lok's komment descendants.")),
                ("text", models.TextField(blank=True, default="", help_text="The plain-text rendering of the descendant tree's leaves, derived on write. Searchable; never authoritative over `descendants`.")),
                ("mentions", models.JSONField(default=list, help_text="Subject ids mentioned in the descendant tree, extracted on write. Strings, the same vocabulary as `Assertion.subject` — the evidence layer holds no user rows.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assertion", models.ForeignKey(help_text="The act of commenting: who said it, with which app, and when.", on_delete=django.db.models.deletion.PROTECT, related_name="comments", to="evidence.assertion")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="authentikate.organization")),
                ("parent", models.ForeignKey(blank=True, help_text="The comment this replies to, for threading. PROTECT where lok cascades: nothing here deletes.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="replies", to="evidence.comment")),
                ("structure", models.ForeignKey(help_text="The external datum this remark is about. The structure carries the thread.", on_delete=django.db.models.deletion.PROTECT, related_name="comments", to="evidence.structure")),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "all_objects",
                "indexes": [models.Index(fields=["organization", "structure", "-created_at"], name="evidence_co_organiz_733348_idx"), models.Index(fields=["organization", "parent"], name="evidence_co_organiz_c0fd8b_idx")],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
