# Generated by Django 6.0.3 on 2026-09-04 07:00
"""Confidence is a property of any claim (RFC 0016).

`Metric` had it; `Instance`, `Link` and `Standing` get the same nullable float.
Nullable and unbackfilled on purpose: nobody scored the existing claims, and
a null is what a `CONFIDENCE` rule refuses to admit. The check constraint on
all four tables refuses a number outside [0, 1] from any writer — the API
refuses it first, the database refuses it last. Adding a column is DDL, which
the append-only triggers do not gate.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('evidence', '0011_every_claim_has_a_time_of_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='confidence',
            field=models.FloatField(blank=True, help_text='How sure the claimant was, 0 to 1. Null means they gave no number — which is not 1.0 and not 0.0: a `CONFIDENCE` rule admits only claims that carry one (RFC 0016).', null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='confidence',
            field=models.FloatField(blank=True, help_text='How sure the claimant was, 0 to 1. Null means they gave no number — which is not 1.0 and not 0.0: a `CONFIDENCE` rule admits only claims that carry one (RFC 0016).', null=True),
        ),
        migrations.AddField(
            model_name='standing',
            name='confidence',
            field=models.FloatField(blank=True, help_text='How sure the claimant was, 0 to 1. Null means they gave no number — which is not 1.0 and not 0.0: a `CONFIDENCE` rule admits only claims that carry one (RFC 0016).', null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='confidence',
            field=models.FloatField(blank=True, help_text='How sure the claimant was, 0 to 1. Null means they gave no number — which is not 1.0 and not 0.0: a `CONFIDENCE` rule admits only claims that carry one (RFC 0016).', null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='confidence_type',
            field=models.CharField(blank=True, help_text="What kind of number `confidence` is — a method's own score, a p-value. Metric-only: it annotates a measurement method.", max_length=1000, null=True),
        ),
        migrations.AddConstraint(
            model_name='instance',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='instance_confidence_in_unit_interval'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='link_confidence_in_unit_interval'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='metric_confidence_in_unit_interval'),
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='standing_confidence_in_unit_interval'),
        ),
    ]
