# Generated by Django 6.0.3 on 2026-09-04 16:44
"""A claim can cite the claims it came from (RFC 0017).

`Link.Kind.DERIVED_FROM`: a choices change only — the refs were always opaque
and `kind` was always the discriminator, so lineage needs no column.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0012_confidence_is_a_property_of_any_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='kind',
            field=models.CharField(choices=[('informs', 'Informs'), ('relation', 'Relation'), ('structure_relation', 'Structure relation'), ('measurement', 'Measurement'), ('participates_as_input', 'Participates as input'), ('participates_as_output', 'Participates as output'), ('classifies', 'Classifies'), ('same_as', 'Same as'), ('derived_from', 'Derived from')], max_length=32),
        ),
    ]
