# Generated by Django 5.2 on 2025-11-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entitycategory_variable_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphquery',
            name='node_category',
            field=models.ForeignKey(default=None, help_text='The category this query is associated if its a node_list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_queries', to='core.nodecategory'),
        ),
    ]
