# Generated by Django 5.2 on 2025-11-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_entitycategory_variable_definitions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptor',
            old_name='name',
            new_name='key',
        ),
        migrations.AlterUniqueTogether(
            name='descriptor',
            unique_together={('category', 'key')},
        ),
    ]
