# Generated by Django 5.2 on 2026-02-04 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_name_descriptor_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version of this schema (e.g., '1.0.0')",
                        max_length=100,
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="Sequential index of this schema version (auto-incremented)"
                    ),
                ),
                (
                    "definition",
                    models.JSONField(help_text="The full GraphDefinitionModel as JSON"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the currently active schema for the graph",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of changes in this schema version",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this schema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="The graph this schema belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to="core.graph",
                    ),
                ),
            ],
            options={
                "ordering": ["-index"],
                "unique_together": {("graph", "index"), ("graph", "version")},
            },
        ),
    ]
